Functional Tests Rit Completion
ZupIT/ritchie-cli pull request #1010
Opened 2021-07-13 18:05 UTC by maurineimirandazup

### Description

Functional tests of the command `rit completion`
### How to verify it
You can verify on menu Actions or submit changes on the files listed in workflow  
### Changelog

2021-07-16 14:06 UTC, lucasdittrichzup approved these changes

2021-07-16 14:34 UTC, GuillaumeFalourd requested changes

2021-07-16 14:34 UTC, GuillaumeFalourd commented on .github/workflows/test-completion-command.yml
> +          rit init --sendMetrics="no" --addCommons="no" --runType="local"
You should add the `rit init` command inside a `- name: RIT INIT command (1)` step to keep all workflows and OS executions standardized.

2021-07-22 03:06 UTC, maurineimirandazup commented on .github/workflows/test-completion-command.yml
> +          rit init --sendMetrics="no" --addCommons="no" --runType="local"
Done.

2021-07-22 13:20 UTC, GuillaumeFalourd approved these changes
👍🏼

2021-07-22 13:26 UTC, merged