Add `formula.yml` support to pre_run
ZupIT/ritchie-cli pull request #1018
Opened 2021-08-17 13:13 UTC by GuillaumeFalourd

Signed-off-by: GuillaumeFalourd <guillaume.falourd@zup.com.br>

### Description

- Add support to read `formula.yml` file (if present) instead of `config.json` file.

### How to verify it

- Add a `formula.yml` file to the formula (at the formula root) with the same informations contained in the `config.json` file.

### Changelog

- Add support to read `formula.yml` file

### Verified

- [ ] Linux
- [x] MacOS
- [ ] Windows

2021-08-30 00:34 UTC, fabianofernandeszup requested changes
Running on linux worked, but using docker gave an error.
I believe that the adjustment made in local/pre_run.go should also be made in docker/pre_run.go

![image](https://user-images.githubusercontent.com/58859234/131270738-b59f6f9f-3a52-4738-9180-847c4536e252.png)

2021-08-30 20:57 UTC, maurineimirandazup approved these changes

2021-08-30 21:49 UTC, lucasdittrichzup commented on pkg/formula/runner/docker/pre_run.go
> +	configFormat := "yml"
what do you think of the `json` and `yml` values like const?

2021-08-30 21:49 UTC, lucasdittrichzup commented on pkg/formula/runner/docker/pre_run.go
> +		configPath = def.ConfigPath(formulaPath)
In order to make the code more readable, I was thinking of separating the operations into other functions (one to check the file type and one to read the file, for example), what do you think about that?

2021-08-30 21:49 UTC, lucasdittrichzup commented on pkg/formula/runner/local/pre_run.go
> +		}
since `local` and `docker` have the same functionality in this part, what do you think about making these operations more generic to avoid code duplication?

2021-08-31 13:13 UTC, GuillaumeFalourd commented on pkg/formula/runner/docker/pre_run.go
> +	configFormat := "yml"
Done 👍🏼

2021-08-31 14:22 UTC, GuillaumeFalourd commented on pkg/formula/runner/local/pre_run.go
> +		}
I created a new method on another classe to avoid code repetition 👍🏼

2021-08-31 14:23 UTC, GuillaumeFalourd commented on pkg/formula/runner/docker/pre_run.go
> +		configPath = def.ConfigPath(formulaPath)
I tried to do it, but couldn't find an elegant solution, so I left it the way it was with a few comments to make it more readable. If you've got an idea of how to to it another way, let me know 👍🏼

2021-08-31 14:46 UTC, lucasdittrichzup approved these changes

2021-09-01 14:09 UTC, merged