feat: add repo-zip command
ZupIT/ritchie-cli pull request #1044
Opened 2021-09-21 15:06 UTC by lucasdittrichzup

### Description
This PR adds the `zipremote` provider and `add repo-zip` command.

### How to verify it
Run `rit add repo-zip`

### Changelog
Add the `zipremote` provider and `add repo-zip` command.

2021-09-21 17:05 UTC, GuillaumeFalourd requested changes
A few observations to standardise 👍🏼

2021-09-21 17:05 UTC, GuillaumeFalourd commented on pkg/cmd/add_repo_zip.go
> +	return formula.Repo{
You should standardise the method's returns: `return repo, nil` as for the `resolveFlags` method. Or IsLocal:       `return formula.Repo{...}, nil` as the `resolveInput` method.

2021-09-21 17:05 UTC, GuillaumeFalourd commented on pkg/cmd/add_repo_zip.go
> +	ErrVersionNotEmpty = "the version field must not be empty"
To follow the same pattern that for `ErrRepoNameNotEmpty`, you should use `ErrVersionNotEmpty = erros.New("the version field must not be empty")` here instead of using the string value directly.

2021-09-21 17:05 UTC, GuillaumeFalourd commented on pkg/formula/repo/creator.go
> +	zipball, err := git.Repos.Zipball(repoInfo, repo.Version.String()) // Download zip repository from provider
zipball? 🤔

2021-09-21 17:05 UTC, GuillaumeFalourd commented on pkg/git/zipremote/repository.go
> +func (re RepoManager) Zipball(info git.RepoInfo, version string) (io.ReadCloser, error) {
zipball? 🤔

2021-09-21 18:13 UTC, lucasdittrichzup commented on pkg/cmd/add_repo_zip.go
> +	return formula.Repo{
done!

2021-09-21 18:14 UTC, lucasdittrichzup commented on pkg/cmd/add_repo_zip.go
> +	ErrVersionNotEmpty = "the version field must not be empty"
done!

2021-09-21 18:15 UTC, lucasdittrichzup commented on pkg/formula/repo/creator.go
> +	zipball, err := git.Repos.Zipball(repoInfo, repo.Version.String()) // Download zip repository from provider
this is a standard used in all providers.

2021-09-21 18:15 UTC, lucasdittrichzup commented on pkg/git/zipremote/repository.go
> +func (re RepoManager) Zipball(info git.RepoInfo, version string) (io.ReadCloser, error) {
this is a standard used in all providers.

2021-09-21 18:32 UTC, GuillaumeFalourd submitted a review, later dismissed

2021-09-22 14:55 UTC, GuillaumeFalourd approved these changes
LGTM 👍🏼

2021-09-22 14:58 UTC, merged