[Feature] - #134 - delete formula
ZupIT/ritchie-cli pull request #447
Opened 2020-08-18 17:49 UTC by JoaoDanielRufino

**- What I did**
Created rit delete formula command

**- How to verify it**
`rit delete formula`

**- Description for the changelog**
rit delete formula command

2020-08-20 20:03 UTC, kaduartur commented on pkg/stdin/stdin.go
> +func WriteToStdin(content string) (tmpfile *os.File, oldStdin *os.File, error error) {
you can check how to test stdin in this [file](https://github.com/ZupIT/ritchie-cli/blob/master/pkg/cmd/init_test.go)

2020-08-31 15:10 UTC, brunasilvazup commented
Hi,
I noticed that you made the changes required by a reviewer and did not request the review again.

![aa](https://user-images.githubusercontent.com/67295691/91735660-fc562000-eb82-11ea-8357-ae3d7187af2a.png)

It is important to remember this functionality of github, that when you make the required modifications it is necessary to request the review again from the person who requested the changes, to mark that they were developed.

2020-08-31 21:07 UTC, brunasilvazup commented on pkg/cmd/delete_formula_test.go
> +	fmt.Println("JSON: " + json)
Should this print exist?

2020-09-01 13:50 UTC, joaorufinozup commented on pkg/cmd/delete_formula_test.go
> +	fmt.Println("JSON: " + json)
I forgot to remove

2020-09-01 20:12 UTC, brunasilvazup commented on pkg/cmd/delete_formula.go
> +		Workspace string   `json:"workspace"`
I noticed in the code that the workspace is the path of the workspace, as we have the name and the path would be good to make explicit in the variable, do you think it is valid?

2020-09-01 20:15 UTC, brunasilvazup commented on pkg/cmd/delete_formula.go
> +		Groups    []string `json:"groups"`
It is also not very intuitive here to supply a string.

It would be much simpler for the user to provide the command of the formula he wants to exclude, for example 'rit test formula' and the function to split the string.

Could you make that change?

2020-09-01 21:19 UTC, joaorufinozup commented on pkg/cmd/delete_formula.go
> +		Workspace string   `json:"workspace"`
I will change it to WorkspacePath

2020-09-01 21:20 UTC, joaorufinozup commented on pkg/cmd/delete_formula.go
> +		Groups    []string `json:"groups"`
Sure

2020-09-02 14:11 UTC, brunasilvazup commented on pkg/cmd/delete_formula.go
> +func (d deleteFormulaCmd) readFormulas(dir string) ([]string, error) {
Hi,
we recently changed `readFormulas` in `buildFormulas.go` to fix a bug, it would be interesting for you to execute the change here as well.

>https://github.com/ZupIT/ritchie-cli/pull/478/files#diff-d422072c7f1366b8e901575179f6864c

2020-09-02 14:13 UTC, brunasilvazup commented on pkg/cmd/delete_formula.go
> +	if err := ioutil.WriteFile(filepath.Join(d.ritchieHomeDir, "repos", "local", "tree.json"), jsonString, os.ModePerm); err != nil {
We have used the functions of the `stream` package instead of` ioutil`, because as interfaces are able to run the tests with mock.

It would be interesting to use it in new codes like yours, can you make that change?

2020-09-03 21:56 UTC, kaduartur requested changes

2020-09-03 21:56 UTC, kaduartur commented on pkg/cmd/delete_formula.go
> +var ErrCouldNotFindFormula = errors.New(msgFormulaNotFound)
could you simplify variable declaration?
For example:
```go
var(
  ErrA = ""
  ErrB = ""
)
```

2020-09-03 21:56 UTC, kaduartur commented on pkg/cmd/delete_formula.go
> +			err := d.deleteFormula(ritchieLocalWorkspace, groups, 0)
Could you simplify the error check?
For example:
```go
if err := d.deleteFormula(ritchieLocalWorkspace, groups, 0); err != nil {
  return err
}
```

2020-09-03 21:56 UTC, kaduartur commented on pkg/cmd/delete_formula.go
> +			err = d.recreateTreeJson(ritchieLocalWorkspace)
Could you simplify the error check?

2020-09-03 21:56 UTC, kaduartur commented on pkg/cmd/delete_formula.go
> +		err := os.RemoveAll(path)
Could you simplify the error check?

2020-09-03 21:56 UTC, kaduartur commented on pkg/cmd/delete_formula.go
> +	err := d.deleteFormula(newPath, groups, index+1)
Could you simplify the error check?

2020-09-03 21:56 UTC, kaduartur commented on pkg/cmd/delete_formula.go
> +	err = d.fileManager.Write(filepath.Join(d.ritchieHomeDir, "repos", "local", "tree.json"), jsonString)
Could you simplify the error check and create a variable for filepath.Join()?

2020-09-03 21:56 UTC, kaduartur commented on pkg/cmd/delete_formula.go
> +	var path = workspace
Could you use the workspace variable and not create a new path variable?

2020-09-03 21:56 UTC, kaduartur commented on pkg/cmd/delete_formula.go
> +	if len(groups) > 0 && groups[0] == "rit" {
Could you use `cmdUse` const here?

2020-09-03 22:39 UTC, victor-schumacher approved these changes

2020-09-04 13:04 UTC, kaduartur approved these changes
Good job! 🚀

2020-09-04 13:05 UTC, kaduartur commented
/merge qa

2020-09-04 13:21 UTC, brunasilvazup approved these changes

2020-09-04 13:31 UTC, brunasilvazup requested changes
Still in bug fixes.

2020-09-04 13:47 UTC, brunasilvazup submitted a review, later dismissed

2020-09-04 13:47 UTC, brunasilvazup commented
/merge qa

2020-09-04 13:59 UTC, lucasdittrichzup approved these changes

2020-09-04 13:59 UTC, lucasdittrichzup commented on pkg/cmd/delete_formula.go
> +		// rit my amazing formula -> ['my', 'amazing', 'formula']
is this comment is really necessary?

2020-09-04 14:05 UTC, joaorufinozup commented on pkg/cmd/delete_formula.go
> +		// rit my amazing formula -> ['my', 'amazing', 'formula']
It facilitates the understanding of what the function does, do you want me to remove it?

2020-09-04 18:17 UTC, brunasilvazup commented
/merge qa

2020-09-08 19:41 UTC, kaduartur commented
/merge qa

2020-09-09 18:59 UTC, lucasdittrichzup approved these changes

2020-09-09 21:57 UTC, kaduartur commented
/merge qa

2020-09-14 18:09 UTC, victor-schumacher approved these changes

2020-09-14 21:41 UTC, kaduartur approved these changes

2020-09-14 21:41 UTC, merged