[feature] - rit delete workspace
ZupIT/ritchie-cli pull request #481
Opened 2020-08-27 23:12 UTC by JoaoDanielRufino

Signed-off-by: JoaoDanielRufino <joaodaniel0405@gmail.com>

**- What I did**
Added rit delete workspace command

**- How to verify it**
`rit delete workspace`

**- Description for the changelog**
rit delete workspace command

2020-09-04 13:25 UTC, victor-schumacher commented on pkg/cmd/delete_workspace.go
> +		} else if !ans {
i think ```else```  is not necessary since you return err on 88

2020-09-04 13:25 UTC, victor-schumacher commented on pkg/cmd/delete_workspace.go
> +	workspacePath = workspaces[workspaceName]
this cannot be created using := ?

2020-09-08 18:46 UTC, kaduartur requested changes

2020-09-08 18:46 UTC, kaduartur commented on pkg/cmd/delete_workspace.go
> +		wspace, err := WorkspaceListInput(workspaces, d.inList)
could you check if workspaces are empty?
because when removing the local workspace I get an error "please provide options to select from"

2020-09-09 22:09 UTC, kaduartur requested changes

2020-09-09 22:09 UTC, kaduartur commented on pkg/formula/workspace/workspace.go
> +	if m.file.Exists(m.workspaceFile) {
you could use the List method and just check if the workspace is valid on [line 80](https://github.com/ZupIT/ritchie-cli/pull/481/files#diff-3b698383ba1651faf9648d74fac6d326R80)

2020-09-16 12:58 UTC, victor-schumacher submitted a review, later dismissed

2020-09-18 20:18 UTC, kaduartur submitted a review, later dismissed

2020-09-21 15:39 UTC, kaduartur approved these changes

2020-09-21 15:39 UTC, kaduartur commented
/merge qa

2020-09-21 16:17 UTC, kaduartur requested changes

2020-09-21 16:17 UTC, kaduartur commented on pkg/formula/workspace/workspace.go
> +	if _, exists := workspaces[workspace.Name]; exists {
When I try to delete the default workspace I receive ErrInvalidWorkspace, because the ritchie doesn't save the default workspace in formula_workspaces.json

2020-09-21 19:46 UTC, kaduartur approved these changes

2020-09-21 19:47 UTC, kaduartur commented
/merge qa

2020-09-21 21:05 UTC, merged