List workspace command
ZupIT/ritchie-cli pull request #485
Opened 2020-08-28 17:44 UTC by henriquemoraeszup

## Description

As a CLI enhancement from the Adoption team. The user can now list his current workspaces.

The code has also been slightly refactored around the `workspace` module:

* The `Validate` method has been removed and its content moved inside `Add` because every occurrence of `Validate` happened after an `Add`
* All workspace-related logic has been moved inside the module. External files would always check for default workspaces to add a new one if necessary. Now, commands like `build formula` and `create formula` just call `workspace.Add` unconditionally and let the logic be handled inside.
* Other files would also handle the addition of a default workspace to its listing method. This logic has also been moved inside the `workspace.List` itself

## Description for the changelog
Added `rit list workspace` command

2020-09-04 15:44 UTC, kaduartur approved these changes
Good job!

I'm waiting for the merger of the `master` branch into` feature/list-workspace`, to proceed with the merger in QA 🚀

2020-09-04 17:44 UTC, henriquemoraeszup commented
Resolved conflict

2020-09-08 13:03 UTC, kaduartur commented
@henriquemoraeszup could you check [Lint](https://app.circleci.com/pipelines/github/ZupIT/ritchie-cli/1908/workflows/cfda028e-08a9-4bc3-815d-36183e407c1a/jobs/7303)?

2020-09-14 21:44 UTC, kaduartur submitted a review, later dismissed

2020-09-14 21:44 UTC, kaduartur commented
/merge qa

2020-09-16 13:00 UTC, victor-schumacher submitted a review, later dismissed

2020-09-17 21:42 UTC, brunasilvazup requested changes

2020-09-17 21:57 UTC, brunasilvazup commented on cmd/main.go
> +	listCmd.AddCommand(listWorkspaceCmd)
And add the new command in `api.go` to update `CoreCmds` list, it's is used in completion terminal.

2020-09-18 18:52 UTC, henriquemoraeszup commented on cmd/main.go
> +	listCmd.AddCommand(listWorkspaceCmd)
nice, I wonder if we could have some sort of automatic indexing for completion of core commands. Did not know about this file

2020-09-18 19:01 UTC, henriquemoraeszup commented on pkg/cmd/list_workspace_test.go
> +	finderTutorial := rtutorial.NewFinder(os.TempDir(), stream.NewFileManager())
Mocks are useful for many different cases especially in our project. But in general, the less mocked the code the better. Think that we are substituting real predictable behavior by a stub that will always respond with success. It is possible that a mocked passing module might break in production because it received a set of inputs it cannot handle. In such case, if tests were passing the parameters to the real module it could have been prevented

2020-09-18 19:59 UTC, henriquemoraeszup commented on pkg/cmd/create_formula.go
> -
We do, however I feel that knowing how to list the default workspace should be a responsibility of the workspace lister. Image that formula creator **and** builder were implementing this and then another command would have to do the same. The dev would have to know that they need to include this rule they should not even know about. 

So by calling `list`, the lister complements with the default one when it returns

2020-09-18 20:07 UTC, henriquemoraeszup commented on pkg/formula/workspace.go
> -}
thanks for noting that, I will update accordingly, I have removed the `validate` method because every occurrence of `validate` was followed by `add` proving there is no reason to decouple both. So validation logic still exists, but inside the `Add` method

2020-09-18 20:47 UTC, kaduartur commented on pkg/cmd/list_workspace_test.go
> +	finderTutorial := rtutorial.NewFinder(os.TempDir(), stream.NewFileManager())
In many cases, mocks don't make sense, but in this particular test, you are already mocking WorkspaceLister. Why not mock tutorial too? Thinking that find tutorial always returns true and tries to search for a file that doesn't exist in your /tmp folder

2020-09-18 20:59 UTC, henriquemoraeszup commented on pkg/cmd/list_workspace_test.go
> +	finderTutorial := rtutorial.NewFinder(os.TempDir(), stream.NewFileManager())
Makes sense, will do

2020-09-22 18:54 UTC, brunasilvazup commented on pkg/formula/workspace/workspace.go
> +	workspaces[formula.DefaultWorkspaceName] = m.defaultWorkspaceDir
As we talked about, the normal flow is going out in some of the ifs and is not listing the default workspace.
Causing difficulties in the create formula for standard users.
Could you test and fix that?

2020-09-22 19:23 UTC, henriquemoraeszup commented on pkg/formula/workspace/workspace.go
> +	workspaces[formula.DefaultWorkspaceName] = m.defaultWorkspaceDir
nice catch

2020-10-13 14:11 UTC, brunasilvazup approved these changes
I left a few comments, but that's fine by me.

2020-10-16 11:12 UTC, victorschumacherzup approved these changes

2020-10-19 14:09 UTC, henriquemoraeszup commented
/merge qa

2020-10-19 17:56 UTC, kaduartur commented
/merge qa

2020-10-19 18:09 UTC, lucasdittrichzup approved these changes

2020-10-20 14:12 UTC, merged