add check for http status
ZupIT/ritchie-cli pull request #499
Opened 2020-09-04 15:09 UTC by victor-schumacher

**- What I did**

Add a http status check when request for stable version

**- How to verify it**

changing the stable version url for some url which don't return 200 and run ``` rit upgrade ```

**- Description for the changelog**

Add a http status check when request for stable version

2020-09-04 15:54 UTC, lucasdittrichzup approved these changes

2020-09-04 16:57 UTC, brunasilvazup approved these changes
You have some functional tests of teams breaking in the build, but otherwise the functionality is ok.

2020-09-04 21:08 UTC, victor-schumacher commented
i commented my changes to test the only pipeline, and it breaks

2020-09-04 22:20 UTC, kaduartur commented
> I commented my changes to test the only pipeline, and it breaks

The ritchie-server (https://ritchie-server.itiaws.dev) is down, try again later!

2020-09-08 13:15 UTC, victor-schumacher commented
> > I commented my changes to test the only pipeline, and it breaks
> 
> The ritchie-server (https://ritchie-server.itiaws.dev) is down, try again later!
Hi @kaduartur, i tried now but still failing, is there any specific time?

2020-09-08 14:59 UTC, victor-schumacher commented
> > > I commented my changes to test the only pipeline, and it breaks
> > 
> > 
> > The ritchie-server (https://ritchie-server.itiaws.dev) is down, try again later!
> > Hi @kaduartur, i tried now but still failing, is there any specific time?

Since the QA environment used on team's functional test was removed, we are removing this step from pipeline too.

2020-09-09 21:56 UTC, kaduartur requested changes

2020-09-09 21:56 UTC, kaduartur commented on pkg/version/version.go
> +	if err != nil || response.StatusCode != http.StatusOK {
I think that when StatusCode isn't 200 the err can be nil and return this not make sense. 

Could you create a new error type and create a new test for this case?

2020-09-14 14:13 UTC, victor-schumacher commented on pkg/version/version.go
> +	if err != nil || response.StatusCode != http.StatusOK {
Thanks for the advice, that's so true.
Done.

2020-09-14 21:46 UTC, kaduartur approved these changes

2020-09-15 14:21 UTC, merged