Regex type to config.json
ZupIT/ritchie-cli pull request #512
Opened 2020-09-10 14:22 UTC by JoaoDanielRufino

Signed-off-by: JoaoDanielRufino <joaodaniel0405@gmail.com>

**- What I did**
Added regex type to config.json to check if user input is in accordance with he specified regex in config.json, if not, it will print the mismatchText message and wait for a valid input

**- How to verify it**
Inside config.json include: 
"pattern": {
       "regex": "your_regex",
       "mismatchText": "your mismatch text"
}

**- Description for the changelog**
Regex type to config.json

2020-09-16 13:18 UTC, victor-schumacher commented on pkg/formula/runner/inputs.go
> +					inputVal, err = in.textRegexValidator(input)
What you think about a validate function? The same logic is written on 221.

2020-09-16 13:22 UTC, victor-schumacher commented on pkg/formula/runner/inputs.go
> +			inputVal, err = in.InputText.Text(input.Label, validate)
It seems like the err varible is overwritten on 225, is it used for anything?

2020-09-16 13:23 UTC, victor-schumacher commented on pkg/formula/runner/inputs.go
> +		return value <= input.Condition.Value, nil
nice, for me it got much more readable

2020-09-16 14:22 UTC, joaorufinozup commented on pkg/formula/runner/inputs.go
> +			inputVal, err = in.InputText.Text(input.Label, validate)
I have just followed the logic that was written before. It was being overwritten to just return at the end of the function

2020-09-16 18:57 UTC, victor-schumacher commented on pkg/formula/runner/inputs.go
> +			inputVal, err = in.InputText.Text(input.Label, validate)
Sure, what you think about check the error or ignore it?

2020-09-16 19:22 UTC, joaorufinozup commented on pkg/formula/runner/inputs.go
> +			inputVal, err = in.InputText.Text(input.Label, validate)
I am going to check it

2020-09-23 22:36 UTC, kaduartur requested changes
Waiting for your changes. Good job!

2020-09-23 22:36 UTC, kaduartur commented on pkg/formula/runner/inputs.go
> +				} else {
could you remove `else` statement and add `break`?

2020-09-23 22:36 UTC, kaduartur commented on pkg/formula/runner/inputs.go
> +			inputVal, err = in.textRegexValidator(input)
could you return `in.textRegexValidator(input)`and remove `else` statement?

2020-09-23 22:36 UTC, kaduartur commented on pkg/formula/runner/inputs_test.go
> +func TestInputManager_RegexType(t *testing.T) {
Could you create a table test to following the Golang tests standard and add more field for **inputJson?**

2020-09-24 18:34 UTC, joaorufinozup commented on pkg/formula/runner/inputs.go
> +				} else {
I did not understand, because if the break the for loop will end, is this the correct behavior that you want?

2020-09-28 21:41 UTC, brunasilvazup commented on pkg/formula/runner/inputs.go
> +					}
Hello @JoaoDanielRufino ,

I was testing the regex with the required attribute and it didn't work well.
If I have an input that is optional (required == false) and a regex, I can't pass an empty string (which would be not to send the same one).

And thinking about a solution I saw that the regex (when existing) would be another validator of the input string.

I thought about changing the name of the function `textRegexValidator` to` textValidator` and putting in it all the needs of this string entry:

 - a part validating the required
 - Other part of the regex itself (with or without the need for it - 
Using else if there `if in.hash Regex (input) {`


Similar to https://github.com/ZupIT/ritchie-cli/pull/544/files in the`pkg/cmd/create_formula.go` file and function `formulaCommandValidator`.

If you want to talk about this solution just let me know.

2020-09-29 20:41 UTC, brunasilvazup approved these changes
LGTM

2020-09-29 21:39 UTC, henriquemoraeszup commented on pkg/formula/runner/docker/runner_test.go
> +	return "mocked text", nil
can we have a dynamic parameter here?

2020-10-05 17:52 UTC, henriquemoraeszup approved these changes

2020-10-05 17:53 UTC, kaduartur approved these changes

2020-10-05 17:53 UTC, merged