add metrics acceptance question info
ZupIT/ritchie-cli pull request #537
Opened 2020-09-18 18:20 UTC by victor-schumacher

**- What I did**
added metrics acceptance question info

**- How to verify it**
Check metabase or log the struct

**- Description for the changelog**
added metrics acceptance question info

2020-09-21 14:08 UTC, lucasdittrichzup submitted a review, later dismissed

2020-09-21 15:33 UTC, kaduartur requested changes

2020-09-21 15:33 UTC, kaduartur commented on pkg/cmd/init.go
> +		metricManager := metric.NewHttpSender(metric.ServerRestURL, http.DefaultClient)
could you receive MetricManager in your constructor?

2020-09-21 19:40 UTC, victor-schumacher commented on pkg/cmd/init.go
> +		metricManager := metric.NewHttpSender(metric.ServerRestURL, http.DefaultClient)
yes! Done in 9e9049c15e460fe853a266f2a6be23f73a5456a2.

2020-09-21 21:15 UTC, kaduartur requested changes

2020-09-21 21:15 UTC, kaduartur commented on pkg/cmd/init.go
> +			Id: "rit_init",
you must create a new Id for this metric because ** rit_init ** will be sent when the rit init command ends

2020-09-22 13:02 UTC, brunasilvazup approved these changes

2020-09-22 13:27 UTC, kaduartur approved these changes
LGTM!

2020-09-22 14:16 UTC, merged