Prompt to auto rebuild formula on source modifications
ZupIT/ritchie-cli pull request #578
Opened 2020-10-02 10:28 UTC by gabriel-pinheiro

**- What I did**
Now, when there are changes in a formula, Ritchie will ask the user whether he wants to run it as is or recompile it automatically before running

**- How to verify it**
- Run any formula to have its first build generated
- Modify its source files
- Run it again, you'll be asked to rebuild it again

**- Description for the changelog**
Prompt to auto rebuild formula on source modifications

2020-10-02 10:38 UTC, gabriel-pinheiro commented
You can already use the feature in the branch, it was opened as a Draft because:
- Code will be refactored: I'll extract the building part of the pre_run.go to a new file
- Tests: The changes broke the tests, I'll take a look at it later and create tests for the new feature

In parallel, I'd like to get help from the Ritchie team to make some decisions:
- Currently the modifications are detected by the directory checksum being changed.. I'm saving the checksum of each formula in a separate file under ~/.rit/hashes
Do you think this is a great idea or would it be better to save all of them in a single JSON file like ~/.rit/repos/hashes.json ?
I don't think marshall/unmarshall times would be that big even for users with a lot of formulas

- The message is currently:
"This formula has changed since the last run, would you like to rebuild?"
Is that ok or would you suggest something else?

- I'm afraid hashing time will be too long for formulas with too many files (like NodeJS formulas with huge node_modules folders), what do you think is the best solution to prevent this? Skip the hash when file count is above a threshold? Limit the hash to a certain directory deepness? (would detect most changes but not all of them) Limit the hashing time? Or is that me overworring about it? Afterall, formulas aren't generally that big?

Thank you in advance :D

2020-10-02 13:19 UTC, victor-schumacher requested changes
thanks for contributing!
congrats for your work :1st_place_medal: 
keep going

2020-10-02 13:19 UTC, victor-schumacher commented on pkg/formula/runner/local/pre_run_build.go
> +	}
i think ```getErr``` can be just ```err``` , and be checked right after the operation.
same for ```setErr```

2020-10-02 13:19 UTC, victor-schumacher commented on pkg/formula/runner/local/pre_run_build.go
> +	}
there is a package called `` stream`` with functions for file and dir operations, it might be a good idea to pass it in the constructor, it is much easier to test

2020-10-02 13:19 UTC, victor-schumacher commented on pkg/formula/runner/local/pre_run_build.go
> +	}
could you simplifie the error check here?
and use ```stream.FileWriter```

2020-10-02 13:19 UTC, victor-schumacher commented on pkg/formula/runner/local/pre_run_build.go
> +	_ = os.Mkdir(this.getHashDir(), os.ModePerm)
```stream.DirCreater``` can be a useful here.
why ignore the error?

2020-10-02 13:19 UTC, victor-schumacher commented on pkg/formula/runner/local/pre_run_build.go
> +	return path.Join(this.ritchieHome, hashesPath)
what you think about use filepath.Join? i think ```path.Join``` don't work on windows because of the backslashes

2020-10-02 13:20 UTC, victor-schumacher commented
it stills a draft?

2020-10-02 14:00 UTC, victor-schumacher commented
> You can already use the feature in the branch, it was opened as a Draft because:
> 
> * ~Code will be refactored: I'll extract the building part of the pre_run.go to a new file~ **DONE!**
> * Tests: I still need to create the automated tests for this feature
> 
> In parallel, I'd like to get help from the Ritchie team to make some decisions:
> 
> * Currently the modifications are detected by the directory checksum being changed.. I'm saving the checksum of each formula in a separate file under ~/.rit/hashes
>   Do you think this is a great idea or would it be better to save all of them in a single JSON file like ~/.rit/repos/hashes.json ?
>   I don't think marshall/unmarshall times would be that big even for users with a lot of formulas
> * The message is currently:
>   "This formula has changed since the last run, would you like to rebuild?"
>   Is that ok or would you suggest something else?
> * I'm afraid hashing time will be too long for formulas with too many files (like NodeJS formulas with huge node_modules folders), what do you think is the best solution to prevent this? Skip the hash when file count is above a threshold? Limit the hash to a certain directory deepness? (would detect most changes but not all of them) Limit the hashing time? Or is that me overworring about it? Afterall, formulas aren't generally that big?
> 
> Thank you in advance :D

Nice questions @gabriel-pinheiro .

I think it would be nice to store this data directly on formula, but i dont really know if thats possible.
About the json, i don't think it gonna be useful

The message is very good to me.

I don't know, but i think we can let this to the end, so we can test some formulas and see what happen

2020-10-02 14:57 UTC, gabriel-pinheiro commented
Thanks for the review, @victor-schumacher !
I'll push the changes soon

> I think it would be nice to store this data directly on formula, but i dont really know if thats possible.
About the json, i don't think it gonna be useful

Yeah, that was my first thought, I couldn't really get it working because if we save the checksum file inside the formula directory, the directory checksum itself would change. That way, the next run would prompt to build again (as there was a change, a file (the checksum) was added/changed).
Other than that, all the formula templates would have to be modified to contain that file in their .gitignore, otherwise git would list it as modified every time :/

> The message is very good to me.

Great!

> I don't know, but i think we can let this to the end, so we can test some formulas and see what happen

Nice, I'll push the requested changes and write some tests so we can move to testing the feature

> it stills a draft?
Yeah, I still want to write some automated tests before converting to a PR

2020-10-02 15:01 UTC, gabriel-pinheiro commented on pkg/formula/runner/local/pre_run_build.go
> +	// Test: should rebuild when requested by user
I left them to just remind me of the scenarios I wanted to test, I'll remove them as soon as I commit the tests

2020-10-02 15:54 UTC, gabriel-pinheiro commented on pkg/formula/runner/local/pre_run_build.go
> +	}
I wanted to keep both errors because even when getPreviousHash fails I want updateHash to execute. That way, when the checksum file doesn't exist, updateHash will still run creating it. If I returned right after getPreviousHash, updateHash would run.

I could add a comment to make it clearer, what do you think?

2020-10-02 15:54 UTC, gabriel-pinheiro commented on pkg/formula/runner/local/pre_run_build.go
> +	_ = os.Mkdir(this.getHashDir(), os.ModePerm)
If it fails because the directory already exists, we still want to continue creating the file

If it fails due to something else, the directory will not be created and the Write below it will fail (and that error is treated)

Is that ok or do you suggest another approach?

2020-10-02 16:52 UTC, victor-schumacher commented on pkg/formula/runner/local/pre_run_build.go
> +	}
makes total sense. i think it's a good idea, let's keep the comment on 131, only removing the ```Test:```

2020-10-02 16:54 UTC, victor-schumacher commented on pkg/formula/runner/local/pre_run_build.go
> +	_ = os.Mkdir(this.getHashDir(), os.ModePerm)
no problem to me

2020-10-02 19:19 UTC, henriquemoraes8 commented on pkg/formula/runner/local/pre_run_build.go
> +	currentHash, setErr := prb.updateHash(formulaPath)
I wonder if we just compare the hashes first and only update if they are different we could save some I/O

2020-10-02 19:23 UTC, henriquemoraeszup reviewed
Nice job, just curious, any specific pros and cons you see in using a directory with n hash files instead of a single file with n hash entries?

2020-10-02 19:23 UTC, henriquemoraeszup commented on pkg/formula/runner/local/pre_run_build.go
> +	currentHash, setErr := prb.updateHash(formulaPath)
I wonder if we just compare the hashes first and only update if they are different we could save some I/O

2020-10-02 21:21 UTC, gabriel-pinheiro commented on pkg/formula/runner/local/pre_run_build.go
> +	currentHash, setErr := prb.updateHash(formulaPath)
Great idea! Pushing a commit to change it now

2020-10-02 21:31 UTC, gabriel-pinheiro commented
> Nice job, just curious, any specific pros and cons you see in using a directory with n hash files instead of a single file with n hash entries?

When I initially thought about this, saving all the hashes to a json file seemed like a costly approach as you would have to read and parse all of them to use only one value in the end but thinking better about it... No one is really gonna have enough formulas to make this process slow.

Other things that also came to mind were:
- Deleting repositories would be much easier, to remove the hashes of the repo xpto we'd only need to remove the `~/.rit/hashes/-home-user-.rit-xpto-*` files
- Updating a hash is much cheaper too, in the JSON approad we would need to save the file with all hashes instead of the hash of one formula

Those wouldn't make that big of a difference for the expected formula amount.. Tbh I don't know if it was worth it to use this approach instead of using the (more organized) single file one.

Do you or anyone else have more points to bring about this? I really have no preferred way tbh haha

2020-10-03 11:13 UTC, gabriel-pinheiro commented
By using this version for myself I could notice some improvement points, I'll push them later:
- Building the formula from somewhere else (even the rit build formula) won't update the hash so it'll still prompt you to rebuild. (The fix isn't complicated though, changing it to prompt for rebuild when source changed and bins didn't might be enough, we'll now save two hashes)
- For formulas in the local repository, changes in the workspace (like `~/ritchie-formulas-local/foo/bar`) don't trigger the rebuild as it checks the hash of the repository (`~/.rit/repos/local/foo/bar`) only.

2020-10-05 13:23 UTC, henriquemoraes8 commented
Hi Gabriel, 

> By using this version for myself I could notice some improvement points, I'll push them later:
> 
> * Building the formula from somewhere else (even the rit build formula) won't update the hash so it'll still prompt you to rebuild. (The fix isn't complicated though, changing it to prompt for rebuild when source changed and bins didn't might be enough, we'll now save two hashes)
> * For formulas in the local repository, changes in the workspace (like `~/ritchie-formulas-local/foo/bar`) don't trigger the rebuild as it checks the hash of the repository (`~/.rit/repos/local/foo/bar`) only.

One question does this only apply to the local repo or are all hashes being compared against the ritchie home? Because the intended use is for the user to **not** edit files in the `.rit` directory. The changes should be detected on the workspace path. Let's say I want to run a formula from my `Zup` workspace (`/Users/henriquerusca/Documents/zup/ritchie-formulas-zup`) the editions on this path should trigger the prompt

2020-10-05 13:26 UTC, henriquemoraes8 commented
> > Nice job, just curious, any specific pros and cons you see in using a directory with n hash files instead of a single file with n hash entries?
> 
> When I initially thought about this, saving all the hashes to a json file seemed like a costly approach as you would have to read and parse all of them to use only one value in the end but thinking better about it... No one is really gonna have enough formulas to make this process slow.
> 
> Other things that also came to mind were:
> 
> * Deleting repositories would be much easier, to remove the hashes of the repo xpto we'd only need to remove the `~/.rit/hashes/-home-user-.rit-xpto-*` files
> * Updating a hash is much cheaper too, in the JSON approad we would need to save the file with all hashes instead of the hash of one formula
> 
> Those wouldn't make that big of a difference for the expected formula amount.. Tbh I don't know if it was worth it to use this approach instead of using the (more organized) single file one.
> 
> Do you or anyone else have more points to bring about this? I really have no preferred way tbh haha

Yeah, no strong opinion here, your approach definitely scales, but it never might come to this. The tradeoff here is organisation <> maintenance complexity, thinking about it now, I like the way it is easier to simply delete/ovewrite the whole file, so I am ok with this approach 😄

2020-10-06 10:20 UTC, gabriel-pinheiro commented
> One question does this only apply to the local repo or are all hashes being compared against the ritchie home? Because the intended use is for the user to **not** edit files in the `.rit` directory. The changes should be detected on the workspace path. Let's say I want to run a formula from my `Zup` workspace (`/Users/henriquerusca/Documents/zup/ritchie-formulas-zup`) the editions on this path should trigger the prompt

Yeah I didn't realize this in the first implementation. Now I'm thinking about implementing it for all workspaces, if the formula has changed in one of them, it will prompt to rebuild.

> Yeah, no strong opinion here, your approach definitely scales, but it never might come to this. The tradeoff here is organisation <> maintenance complexity, thinking about it now, I like the way it is easier to simply delete/ovewrite the whole file, so I am ok with this approach

Nice, I'll have to change the structure a bit for the workspace adaptation so I'll also implement this

2020-10-06 17:31 UTC, henriquemoraeszup commented
Hey, this is looking good, just another thing that I remembered to keep in mind. I will try to make the folder structure clear to you:
Currently we can clone a repo or add a workspace to index formulas from anywhere in your file system.
Ritchie will copy the folder structure to the `.rit` path
When you build the formula, it generates a `/bin` folder on the formula directory, not sure if you are hashing just the `src` directly but it could be a good idea since the bin might mess up your hash 😅 

Cheers!

2020-10-06 22:47 UTC, gabriel-pinheiro commented
> Hey, this is looking good, just another thing that I remembered to keep in mind. I will try to make the folder structure clear to you:
> Currently we can clone a repo or add a workspace to index formulas from anywhere in your file system.
> Ritchie will copy the folder structure to the `.rit` path
> When you build the formula, it generates a `/bin` folder on the formula directory, not sure if you are hashing just the `src` directly but it could be a good idea since the bin might mess up your hash 
> 
> Cheers!

Great idea! Yeah, I was hashing everything. So, that means all formula templates keep the code inside `src` right? (btw sorry about the delay, I'll probably be able to start coding the changes in a bit)

2020-10-07 11:47 UTC, gabriel-pinheiro commented
There we go! Now it's looking for changes in the formula on any workspace and only in the `src` folder. This means that changes in the config.json won't trigger the rebuild, is that ok or would going back to the root of the formula preferred?

**Please don't approve this PR yet** as there are three changes I still want to make:
- For some reason the workspace.List() doesn't return the Default workspace so changes there aren't detected yet, I'll fix it later (probably during lunch today)
- I still need to add unit tests to the new implementation
- Change the hashing structure from the "one file per formula" to the .json

PS: I'm using this version myself to create a formula and the prompt to rebuild is sooo good hahaha. No more need to wait for the `rit build formula --watch` to succeed before running the command

2020-10-07 13:17 UTC, henriquemoraeszup commented
Gabriel, no need to fix the list workspace option. It will be fixed on #485 
Nice, can't wait to use it either! hahaha

2020-10-07 17:04 UTC, gabriel-pinheiro commented
> Gabriel, no need to fix the list workspace option. It will be fixed on #485

Oh nice!

> As for the config.json it is not clear for me as well, how would you work the root of the formula given the `bin` folder? 2 hashes? One for the `config.json` and one for the `src`?

I'm not comparing the hash of the workspace to the hash of the repo on ~/.rit, I'm comparing the hash of the workspace to its previous hash. That way, as the bin folder isn't generally in the workspace (unless the user runs the makefile in there instead of letting Ritchie build it), it wouldn't mess the hash

2020-10-07 17:44 UTC, kaduartur requested changes
Good job 🚀 If you need to talk about it, just call me!

2020-10-07 17:44 UTC, kaduartur commented on pkg/formula/runner/pre_run_builder.go
> +func (b PreRunBuilderManager) Build(formulaRelativePath string) {
could you rename the parameter to formulaPath or relativePath?
Go style recommends short variable names

2020-10-07 17:44 UTC, kaduartur commented on pkg/formula/runner/pre_run_builder.go
> +func (b PreRunBuilderManager) getPreviousHash(formulaPath string) (string, error) {
Good practice in go is not to add get in the function name. [Getters in golang](https://golang.org/doc/effective_go.html#Getters)

2020-10-07 17:44 UTC, kaduartur commented on pkg/formula/runner/pre_run_builder.go
> +func (b PreRunBuilderManager) getCurrentHash(formulaPath string) (string, error) {
Good practice in go is not to add get in the function name. [Getters in golang](https://golang.org/doc/effective_go.html#Getters)

2020-10-07 17:44 UTC, kaduartur commented on pkg/formula/runner/pre_run_builder.go
> +func (b PreRunBuilderManager) getHashDir() string {
Do you think that makes sense? it is only used in one place.

2020-10-07 17:44 UTC, kaduartur commented on pkg/formula/runner/pre_run_builder.go
> +	divider := "/"
could you use the `os.PathSeparator` to solve this problem?

2020-10-07 17:44 UTC, kaduartur commented on pkg/formula/runner/pre_run_builder.go
> +func (b PreRunBuilderManager) getHashPath(formulaPath string) string {
Good practice in go is not to add get in the function name. [Getters in golang](https://golang.org/doc/effective_go.html#Getters)

2020-10-07 17:44 UTC, kaduartur commented on pkg/formula/runner/executor.go
> +	ex.preRunBuilder.Build(exe.Def.Path)
I think that you should only execute pre-build when the `exe.Def.RepoName` is **local** because other repositories could not be edited. They reflect the git repositories released!

2020-10-08 11:15 UTC, gabriel-pinheiro commented on pkg/formula/runner/pre_run_builder.go
> +	divider := "/"
Muuch simpler, I didn't know about that one haha! Thanks

2020-10-08 11:27 UTC, gabriel-pinheiro commented on pkg/formula/runner/executor.go
> +	ex.preRunBuilder.Build(exe.Def.Path)
Ohhh great point

When a formula exists locally, `exe.Def.RepoName` will be `local` even if the formula also exists in a remote repo, right? I've done some tests here and it looks like the case but I just want to make sure, maybe it has something to do with priorities.

I'm asking because someone might be developing locally a formula for a repo and the rebuild prompt wouldn't appear.

I'm pushing this change, if we think about something else I can drop the commit

2020-10-08 15:10 UTC, kaduartur commented on pkg/formula/runner/executor.go
> +	ex.preRunBuilder.Build(exe.Def.Path)
If you build a formula from a workspace this formula will be built to the local repo. PS, the local repo has the maximum priority.

2020-10-16 18:50 UTC, henriquemoraeszup reviewed
I think I am good to approve, are we missing something here?

2020-10-16 18:57 UTC, gabriel-pinheiro commented
I still want to add some changes like the .json for the hashes and invalidate the hash on manual builds but I didn't have enough time this week :(

May we wait until Monday?

2020-10-19 12:19 UTC, gabriel-pinheiro commented
Changes made, ready for review again :smiley:

2020-10-19 13:54 UTC, victorschumacherzup submitted a review, later dismissed

2020-10-20 12:43 UTC, henriquemoraeszup approved these changes
![giphy (6)](https://user-images.githubusercontent.com/68074718/96587423-b121d900-12b8-11eb-9f20-00462fc95f09.gif)

2020-10-20 13:20 UTC, brunasilvazup commented on pkg/cmd/mocks_test.go
> +
Hi @gabriel-pinheiro, thanks for contribuition.

When we use `CustomMock`we have the default to make the internal functions customizable.
With the current change, half of the functions would be customized and half not, which can cause confusion in use.

Could you change that part leaving it customizable and also change the name of the mock to what you redefined `WorkspaceAddListValidatorCustomMock` -> `WorkspaceAddListValidateHasherCustomMock`?

2020-10-20 14:15 UTC, henriquemoraeszup commented
@gabriel-pinheiro yours is next to merge, sorry but #485 introduced conflicts 😅

2020-10-20 15:43 UTC, gabriel-pinheiro commented on pkg/cmd/mocks_test.go
> +
Ohh got it! Pushing a commit now to fix it =P

2020-10-20 16:11 UTC, gabriel-pinheiro commented
@brunasilvazup I just pushed the implementation of your suggestions :smile: 

@henriquemoraeszup conflicts resolved =P

2020-10-20 17:05 UTC, brunasilvazup commented on pkg/formula/runner/pre_run_builder_test.go
> +			}
As always an error is returned, we can remove the if and let `test.mustBuild` itself be the answer something like:

```GO
gotBuild := builderMock.HasBuilt()
if gotBuild != test.mustBuild {
	t.Errorf("Got builder %v, want builder %v", gotBuild, test.mustBuild)
}
```


*I put the build result in a variable because it would be used more than once.

** In the ritchie tests we also follow the got - want pattern and always inform the result and the real expected to have more information.

2020-10-20 17:06 UTC, brunasilvazup commented on pkg/formula/runner/pre_run_builder_test.go
> +			}
The same logic could be applied here ...

2020-10-20 17:13 UTC, brunasilvazup commented on pkg/formula/workspace/workspace.go
> +}
This function was removed in the last PR that entered the master, did you keep it because you will use it specifically or was it an error in the merge?

2020-10-20 17:22 UTC, brunasilvazup commented on pkg/formula/runner/pre_run_builder.go
> +	}
If this error (l 119) refers to the error returned from `PreviousHash` should it not be on the line below it (l 111)?

The same condition is used to enter the previous if (l 111), it made me a little confused...

2020-10-20 18:15 UTC, brunasilvazup commented on pkg/formula/workspace/workspace_test.go
> +			}
You can simplify these ifs into one with:
```go
if (err != nil) != (tt.out.err != nil) || (err != nil && err.Error() != tt.out.err.Error()) {
	t.Errorf("Validate(%s) got error '%v', expected error '%v'", tt.name, err, tt.out.err)
}
```
The first part validates whether the expected error (whether nil or not) is different from the one received.
`(err != nil) != (tt.out.err != nil)`

The second part is valid if the error is different from null (`err != nil &&`) if the expected and presented errors are the same.
`(err != nil && err.Error() != tt.out.err.Error())`

2020-10-20 18:24 UTC, brunasilvazup commented on pkg/formula/workspace/workspace_test.go
> +				t.Errorf("Validate(%s) expected hash %s to be written instead of %s", tt.name, string(tt.out.content), string(hashContent))
Useful information:

When we use the `tt.Run` structure it already shows the name of the test when presenting the errors, so we don't need to repeat this information in `t.fail` or `Errorf`:

![Captura de tela de 2020-10-20 15-20-07](https://user-images.githubusercontent.com/67295691/96628235-57d19e00-12e8-11eb-9394-f04c74debb5e.png)

2020-10-20 18:25 UTC, brunasilvazup commented on pkg/formula/workspace/workspace_test.go
> +			}
If you decide to change, change here too.

2020-10-20 18:26 UTC, brunasilvazup requested changes
I left some comments on the testing part, a merge conflict that I think it was and also as a reminder to change the path we talked about.

2020-10-21 10:41 UTC, gabriel-pinheiro commented on pkg/formula/workspace/workspace_test.go
> +			}
Ohh elegant solution! Much simpler

2020-10-21 10:51 UTC, gabriel-pinheiro commented on pkg/formula/runner/pre_run_builder.go
> +	}
Its down there because I want to update the hash (l 112) when reading the previous hash fails (probably because it's the first time hashing a formula).

The if on 111 is for updating the hash when it's the first time hashing a formula (no previous hash, err != nil) or when the previous hash is different from the current one.

Can you think of a better way to convey this idea in the code structure?

2020-10-21 21:03 UTC, brunasilvazup commented on pkg/formula/runner/pre_run_builder.go
> +	}
I understand now.

And about logic, I think it could be improved by isolating the responsibilities.
A function that says whether or not the hash exists for the formula, if not, makes a return and ends.

Then, another function that is `PreviousHash` and then we only check if there was an error (with normal error return - same as line 106), if it is not verified if the hash has changed following the flow.

What do you think?

2020-10-21 21:14 UTC, brunasilvazup commented on pkg/formula/runner/pre_run_builder.go
> +	}
I understand now

2020-10-21 21:36 UTC, brunasilvazup approved these changes
Congratulations on your implementation, ready for QA.

2020-10-22 10:52 UTC, gabriel-pinheiro commented
Yayy thank you all so much :smile: 

Btw, just added the .gif of the implementation to the PR, here it is too:
![rit2](https://user-images.githubusercontent.com/56726395/96862112-6da3a800-143b-11eb-8a4a-a74f399e0356.gif)

2020-10-22 17:50 UTC, brunasilvazup commented
\merge qa

2020-10-22 18:05 UTC, brunasilvazup commented
/merge qa

2020-10-26 12:25 UTC, henriquemoraeszup approved these changes

2020-10-26 12:37 UTC, GuillaumeFalourd commented
Thank you for contributing @gabriel-pinheiro 👍🏼 

Remembering that if you wish to participate the [Zup challenge for the hacktoberfest](https://insights.zup.com.br/hacktoberfest), you'll have to get 2 PR accepted on Zup repositories. Is this your first contribution, or have you submit something to other repositories as well ?

2020-10-26 12:53 UTC, kaduartur approved these changes
LGTM!

2020-10-26 12:54 UTC, merged

2020-10-27 10:50 UTC, gabriel-pinheiro commented
Niiice! Can't wait for its version to be release haha

@GuillaumeFalourd it's my first contribution for Zup's Hacktoberfest, I still want to find another Issue to contribute before the end of the month