Update README file
ZupIT/ritchie-cli pull request #593
Opened 2020-10-05 19:38 UTC by GuillaumeFalourd

**- What I did**

- Update the README file with new formula description picture.
- Text enhancement.

**- How to verify it**

- Check the README file.

**- Description for the changelog**

- README file update.

2020-10-05 20:10 UTC, lucasdittrichzup approved these changes

2020-10-06 13:36 UTC, brunasilvazup approved these changes

2020-10-06 13:46 UTC, brunasilvazup requested changes

2020-10-06 13:48 UTC, brunasilvazup requested changes

2020-10-06 13:48 UTC, brunasilvazup commented on README.md
> +<img class="special-img-class" src="/docs/img/formulas-explanation.png"  alt="Formulas explanation"/>
This image not found `https://github.com/ZupIT/ritchie-cli/docs/img/formulas-explanation.png`

2020-10-06 16:04 UTC, GuillaumeFalourd commented on README.md
> +<img class="special-img-class" src="/docs/img/formulas-explanation.png"  alt="Formulas explanation"/>
It works for me locally, maybe it is because I'm adding the formula image on the README file in this PR ?

2020-10-06 16:31 UTC, brunasilvazup commented on README.md
> +<img class="special-img-class" src="/docs/img/formulas-explanation.png"  alt="Formulas explanation"/>
I think so.

2020-10-06 16:32 UTC, brunasilvazup approved these changes

2020-10-07 13:10 UTC, henriquemoraeszup approved these changes

2020-10-07 17:34 UTC, lucasdittrichzup approved these changes

2020-10-07 17:50 UTC, merged