[Fix] - Searching only for run.sh on docker pre run
ZupIT/ritchie-cli pull request #598
Opened 2020-10-06 17:19 UTC by JoaoDanielRufino

Signed-off-by: JoaoDanielRufino <joaodaniel0405@gmail.com>

**- What I did**
When building a formula with docker on windows, the CLI only checks if there is a run.bat file, but on docker it is necessary to check if there is a run.sh file to build the formula.

**- How to verify it**
Build a formula locally on windows and then run the formula with docker.

**- Description for the changelog**
Check if there is run.sh file when building formula with docker.

2020-10-06 17:29 UTC, GuillaumeFalourd approved these changes

2020-10-07 13:39 UTC, lucasdittrichzup approved these changes

2020-10-08 14:26 UTC, brunasilvazup commented
@JoaoDanielRufino this change its necessary only in windows? If yes, would it be good to specify windows situation in the code?

2020-10-08 14:26 UTC, brunasilvazup requested changes
@JoaoDanielRufino this change its necessary only in windows? If yes, would it be good to specify windows situation in the code?

2020-10-08 19:30 UTC, brunasilvazup commented
> @JoaoDanielRufino this change its necessary only in windows? If yes, would it be good to specify windows situation in the code?
> 
> PS.: I used 'request changes' to discuss this before, not necessarily needs changes.

We talked and I could understand that it is just a check for windows.

2020-10-21 19:21 UTC, kaduartur approved these changes

2020-10-21 19:44 UTC, brunasilvazup approved these changes

2020-10-21 19:46 UTC, merged