Adding developer guide
ZupIT/ritchie-cli pull request #604
Opened 2020-10-13 18:01 UTC by henriquemoraeszup

**- What I did**
* Added a developer guide to explain the project structure.
* Edited the PR template to a more open-ended question like **description** instead of **what I did**

**- Description for the changelog**

Added developer guide

2020-10-13 18:40 UTC, GuillaumeFalourd requested changes

2020-10-13 18:40 UTC, GuillaumeFalourd commented on DEVELOPER_GUIDE.md
> +# Developer guide
I would add a step by step explaining how to build the project and execute a command locally to test new implementations.
What do you think ?

2020-10-13 18:46 UTC, GuillaumeFalourd commented
Add a link to the Developer Guide from the README could be interesting as well.

2020-10-13 21:25 UTC, Harirai commented
I think this will be very helpful for new contributors @henriquemoraeszup Thank you :tada:  for adding this. I have a few suggestions, I hope they'll be apt. :smile: 

Recently while working on the project, I realized that a description on "How to build the project after making changes", would be very helpful for new developers to use the feature they added/updated. (using `make` command and  purpose of Makefile)

Another nice addition to the guide can be "How to run tests locally", for this there is `run-test.sh` file.

2020-10-14 19:44 UTC, henriquemoraeszup commented
Thanks guys for the feedback, after some more meetings with the community I have realised there is still some way to go

2020-10-16 13:47 UTC, GuillaumeFalourd approved these changes

2020-10-16 14:19 UTC, merged