Formula inputs by flags
ZupIT/ritchie-cli pull request #617
Opened 2020-10-15 17:08 UTC by kaduartur

**- What I did**
I allow the formula inputs by flags:
![image](https://user-images.githubusercontent.com/17505818/96160154-f5ddf680-0eeb-11eb-8cf3-456eb167c947.png)

- When an input by the flag is empty the Ritchie call the prompt to the user to insert this value
- Added a new flag named `--non-interactive` to run formulas without interaction, it will only work for formulas with inputs via flags and then evolve to stdin.
- Edited the code owners 
- Created an input resolver for formula runner
- Split the inputs.go into `input/prompt, input/stdin, and input/flag` to make easier the maintainability.

**- How to verify it**
1 - Checkout in this branch
2 - Build Ritchie locally `make build-{your-operational system}` and replace you locally installation
3 - Show your formula flags with `rit formula name --help`, you can see the inputs name such as flags
4 - Run your formulas with flags

**- Description for the changelog**
Allow formula inputs with flags

2020-10-15 18:35 UTC, GuillaumeFalourd requested changes

2020-10-15 18:35 UTC, GuillaumeFalourd commented on .github/ritchie-bot-config.yml
> -    'guillaumefalourd',
This account *GuillaumeFalourd* is corporative (ZupIT)

2020-10-16 01:00 UTC, henriquemoraeszup reviewed
Bravo 👏 still haven't read it all, but I left a suggestion for debate

2020-10-16 12:26 UTC, GuillaumeFalourd commented on pkg/cmd/formula.go
> +		}
I think it makes sense 👍🏼 
I just don't remember when the `STDIN` was implemented why we used the flag and not the `|` detection.

2020-10-20 18:47 UTC, kaduartur commented on pkg/cmd/formula.go
> +		}
it has been defined that each type of input will have its own responsibility, we will remove the necessity to use the --stdin option for formulas and main commands

2020-10-21 00:22 UTC, henriquemoraeszup commented on pkg/formula/input/prompt/prompt.go
> -		case "dynamic":
removing magic strings, nice 👍

2020-10-21 14:34 UTC, kaduartur commented on pkg/formula/input/flag/flag.go
> +	}
Good suggestion, thanks 🚀

2020-10-22 17:51 UTC, henriquemoraeszup approved these changes

2020-10-22 19:01 UTC, kaduartur commented
/merge qa

2020-10-22 20:11 UTC, brunasilvazup commented on .github/OWNERS
> -* @lucasdittrichzup
Shouldn't we keep the reviewers?

2020-10-22 20:31 UTC, brunasilvazup commented on pkg/cmd/formula.go
> +		if changed := flags.Changed(flag.name); changed {
Here you could just leave the `flags.Changed(flag.name)`, what do you think?

2020-10-22 21:08 UTC, brunasilvazup commented on pkg/cmd/formula.go
> +			prompt.Warning("this type of flag is not supported")
Could you add the name of the flag and its type, to give more information, what do you think?

2020-10-22 21:32 UTC, kaduartur commented on pkg/cmd/formula.go
> +		if changed := flags.Changed(flag.name); changed {
OMG, thanks for this review LOL

2020-10-22 21:42 UTC, kaduartur commented on .github/OWNERS
> -* @lucasdittrichzup
this file doesn't work for Github, I created a CODEOWNERS file.

2020-10-22 21:46 UTC, kaduartur commented on pkg/cmd/formula.go
> +			prompt.Warning("this type of flag is not supported")
Nice! 👀

2020-10-23 11:40 UTC, victorschumacherzup approved these changes

2020-10-23 11:44 UTC, victorschumacherzup approved these changes

2020-10-23 12:52 UTC, kaduartur commented
/merge qa

2020-10-26 13:20 UTC, lucasdittrichzup submitted a review, later dismissed

2020-10-27 14:35 UTC, victorschumacherzup approved these changes

2020-10-27 14:35 UTC, victorschumacherzup commented on pkg/cmd/formula.go
> +		switch flag.kind {
nice

2020-10-27 15:15 UTC, lucasdittrichzup approved these changes

2020-10-27 20:29 UTC, kaduartur commented
/merge qa

2020-10-27 20:43 UTC, kaduartur commented
/merge qa

2020-10-28 18:00 UTC, kaduartur commented
/merge qa

2020-10-28 18:02 UTC, kaduartur commented
/merge qa

2020-10-28 18:45 UTC, merged