first part
ZupIT/ritchie-cli pull request #635
Opened 2020-10-27 12:27 UTC by victorschumacherzup

Signed-off-by: victor-schumacher <victorschumacher255@gmail.com>

### Description

### How to verify it

### Changelog

2020-10-27 14:45 UTC, lucasdittrichzup approved these changes

2020-11-11 13:09 UTC, brunasilvazup commented on pkg/formula/input/prompt/prompt.go
> +	defaultFlag, _ := f.GetBool("default")
Technically, this information not change with inputs right?
So, they could if defined before for_of_inputs, in line 80.
Whats do you think?

2020-11-11 13:15 UTC, brunasilvazup approved these changes

2020-11-11 13:18 UTC, henriquemoraeszup requested changes
I thought we were supporting default for stdin and flags as well right?

2020-11-11 13:21 UTC, henriquemoraeszup commented on pkg/formula/input/prompt/prompt.go
> +				}
can you extract this in a method to reduce cognitive complexity?

2020-11-11 13:46 UTC, lucasdittrichzup submitted a review, later dismissed

2020-11-11 13:46 UTC, lucasdittrichzup commented on pkg/formula/input/prompt/prompt_test.go
> +		"default": "test"
is the indentation correct?

2020-11-11 21:32 UTC, victorschumacherzup commented on pkg/formula/input/prompt/prompt_test.go
> +		"default": "test"
Github shows it different then Goland, for example, check line 51 of this file, all the strings looks unformatted. 
Thanks for the observation.

2020-11-11 21:38 UTC, victorschumacherzup commented on pkg/formula/input/prompt/prompt.go
> +	defaultFlag, _ := f.GetBool("default")
You're right, it doesn't change. I put it here to centralize things involved with default flag.
Updated the declaration to line 83 (before) to avoid unnecessarily call it for each input.
Thanks!

2020-11-11 21:40 UTC, victorschumacherzup commented on pkg/formula/input/prompt/prompt.go
> +				}
Sure! Please take a look at d2d32eb327f7d4f0367a415aa7bf1a90ba25e865 and 1ffea15f83d76eab9e9f4cdc9e4c3afc4d657f85
Thanks for the suggeestion

2020-11-12 18:05 UTC, lucasdittrichzup submitted a review, later dismissed

2020-11-12 18:48 UTC, brunasilvazup commented on pkg/formula/input/prompt/prompt.go
> +		}
This else is unclear, as they are returns, just 
```
if items != nil {
			return in.loadInputValList(items, i)
		}
return in.textValidator(i)
```

2020-11-12 18:49 UTC, brunasilvazup submitted a review, later dismissed

2020-11-12 21:01 UTC, victorschumacherzup commented on pkg/formula/input/prompt/prompt.go
> +		}
thanks 2a043f9

2020-11-13 00:24 UTC, lucasdittrichzup approved these changes

2020-11-13 17:02 UTC, lucasdittrichzup commented
/merge qa

2020-11-13 18:00 UTC, henriquemoraes8 approved these changes

2020-11-13 18:01 UTC, henriquemoraeszup approved these changes

2020-11-13 21:14 UTC, lucasdittrichzup commented
congrats man, great job!

2020-11-13 21:31 UTC, merged