add reading and filtering
ZupIT/ritchie-cli pull request #638
Opened 2020-10-27 21:38 UTC by victorschumacherzup

## Description
 :construction: :construction:  :construction: 
# WIP
 :construction: :construction:  :construction: 

### How to verify it

### Changelog

2020-11-03 13:25 UTC, brunasilvazup approved these changes
Hi, i did tests locally and is Ok.

Good job (:

2020-11-03 17:33 UTC, henriquemoraeszup commented on pkg/formula/tree/checker.go
> +		treeArr = append(treeArr, tree)
Could we extract the commands in this step to avoid another double for loop?

2020-11-03 17:33 UTC, henriquemoraeszup commented on pkg/formula/tree/checker.go
> +	msg := fmt.Sprintf("The following formula command are conflicting: %s", lastCommand)
```suggestion
	msg := fmt.Sprintf("The following formula commands are conflicting: %s", lastCommand)
```

2020-11-03 17:33 UTC, henriquemoraeszup commented on pkg/formula/tree/checker.go
> +			duplicatedCommands = append(duplicatedCommands, item)
what happens if we have 3 duplicate commands? Will it be printed twice? We might want to use a set for this data structure, which does not exist in go, but can be attained with a map to bool

https://stackoverflow.com/questions/34018908/golang-why-dont-we-have-a-set-datastructure

2020-11-03 17:33 UTC, henriquemoraeszup commented on pkg/formula/tree/checker_test.go
> +			treeChecker.CheckCommands()
Is there a way we can assert the printed text?

2020-11-03 17:36 UTC, victorschumacherzup commented on pkg/commands/builder.go
> +	createFormulaCmd := cmd.NewCreateFormulaCmd(userHomeDir, createBuilder, tplManager, formulaWorkspace, inputText, inputTextValidator, inputList, tutorialFinder, treeChecker)
line 211

2020-11-03 18:05 UTC, victorschumacherzup commented on pkg/formula/tree/checker.go
> +		treeArr = append(treeArr, tree)
There's one for loop stacking tree's here, i can put another for loop here and remove the filter commands function, but this function seems pretty overload already.

2020-11-03 18:07 UTC, victorschumacherzup commented on pkg/formula/tree/checker.go
> +			duplicatedCommands = append(duplicatedCommands, item)
It will be printed two times since we have 2 duplicates, do you think that's a problem?

2020-11-03 18:35 UTC, henriquemoraeszup commented on pkg/formula/tree/checker.go
> +			duplicatedCommands = append(duplicatedCommands, item)
It is not clear to me when this is printed, can you add a full screenshot of the text?

2020-11-04 12:12 UTC, victorschumacherzup commented on pkg/formula/tree/checker.go
> +			duplicatedCommands = append(duplicatedCommands, item)
this warning show always the last conflicting command, like this:
![image](https://user-images.githubusercontent.com/51962831/98110457-e2380700-1e7d-11eb-9744-d8e1d9970744.png)

2020-11-04 14:09 UTC, henriquemoraeszup commented on pkg/formula/tree/checker.go
> +			duplicatedCommands = append(duplicatedCommands, item)
if you have multiple, shouldnt you newline?

2020-11-04 14:10 UTC, henriquemoraeszup commented on pkg/formula/tree/checker.go
> +		treeArr = append(treeArr, tree)
what if `filterCommands` receives a single tree and returns the command list? I still think we can remove a loop here

2020-11-04 14:25 UTC, henriquemoraeszup commented on pkg/formula/tree/checker.go
> +	msg := fmt.Sprintf("The following formula commands are conflicting: %s", lastCommand)
why are we printing jus a single command? What if we have 2 `rit aws create bucket` and 2 `rit github update repo`?

2020-11-04 14:53 UTC, kaduartur requested changes

2020-11-04 14:53 UTC, kaduartur commented on pkg/formula/tree.go
> +	CheckCommands()
Could you rename this method?
For example:

```go
 type TreeChecker interface {
	Check()
}
// -----------------------------------

commands.Check()

```

2020-11-04 14:53 UTC, kaduartur commented on pkg/formula/tree/checker.go
> +	Dir  stream.DirLister
Why Dir is public?

2020-11-04 14:53 UTC, kaduartur commented on pkg/formula/tree/checker.go
> +	repos, _ := cm.Dir.List(repoDir, false)
I think you can use the `Tree ()` method of the `TreeManager`. It returns a tree by repositories  `map[string]formula.Tree`

2020-11-04 17:33 UTC, victorschumacherzup commented on pkg/formula/tree/checker.go
> +			duplicatedCommands = append(duplicatedCommands, item)
It prints only the last conflicting command, i made this way because if we have lots of commands, this warning will be a spam.

2020-11-04 17:35 UTC, victorschumacherzup commented on pkg/formula/tree/checker.go
> +	msg := fmt.Sprintf("The following formula commands are conflicting: %s", lastCommand)
Imagine printing all commands in a duplicated ```tree.json``` , gonna be like a spam.

2020-11-04 19:46 UTC, victorschumacherzup commented on pkg/formula/tree/checker.go
> +	Dir  stream.DirLister
I was testing something and forgot it. With the Tree method added on 165f5d2918b6ea77f3231136a0311b1bc652bb96, dir is not used anymore. Thanks for the advice.

2020-11-04 19:48 UTC, victorschumacherzup commented on pkg/formula/tree/checker.go
> +	repos, _ := cm.Dir.List(repoDir, false)
It was very useful, this read function has been entirely removed on 165f5d2918b6ea77f3231136a0311b1bc652bb96. Thanks.

2020-11-04 19:50 UTC, victorschumacherzup commented on pkg/formula/tree/checker.go
> +		treeArr = append(treeArr, tree)
nice idea, with the changes on 165f5d2918b6ea77f3231136a0311b1bc652bb96 i removed `readCommands` function

2020-11-05 13:42 UTC, brunasilvazup commented on pkg/formula/formula.go
> +		Default bool
Is this change in your PR or are they remnants of merge?

2020-11-05 13:43 UTC, brunasilvazup commented on pkg/formula/input/prompt/prompt.go
> +func (in InputManager) Inputs(cmd *exec.Cmd, setup formula.Setup, e *pflag.FlagSet) error {
Is this change (this file) in your PR or are they remnants of merge?

2020-11-05 13:49 UTC, brunasilvazup approved these changes

2020-11-05 14:03 UTC, henriquemoraeszup commented on pkg/formula/tree/checker.go
> +			duplicatedCommands = append(duplicatedCommands, item)
So maybe we can add the total amount of conflicting commands as well then

2020-11-06 14:14 UTC, henriquemoraeszup commented on metrics.json
> +}
is this intended?

2020-11-06 14:15 UTC, henriquemoraeszup commented on pkg/formula/input/prompt/prompt.go
> +		// fmt.Println(e.Lookup("--default"))
commented code

2020-11-06 14:16 UTC, henriquemoraeszup commented on pkg/formula/tree/checker.go
> +			duplicateFrequency[item] += 1 // increase counter by 1 if already in the map
I think you can remove the comment, your code is self explanatory =]

2020-11-06 15:21 UTC, victorschumacherzup commented on metrics.json
> +}
removed, thanks for the advice

2020-11-06 15:21 UTC, victorschumacherzup commented on pkg/formula/input/prompt/prompt.go
> +		// fmt.Println(e.Lookup("--default"))
removed

2020-11-06 15:22 UTC, victorschumacherzup commented on pkg/formula/tree/checker.go
> +			duplicateFrequency[item] += 1 // increase counter by 1 if already in the map
sure! removed

2020-11-06 15:26 UTC, victorschumacherzup commented on pkg/formula/tree/checker.go
> +			duplicatedCommands = append(duplicatedCommands, item)
nice! added it

2020-11-06 15:27 UTC, victorschumacherzup commented on pkg/formula/formula.go
> +		Default bool
removed, thanks

2020-11-06 15:27 UTC, victorschumacherzup commented on pkg/formula/input/prompt/prompt.go
> +func (in InputManager) Inputs(cmd *exec.Cmd, setup formula.Setup, e *pflag.FlagSet) error {
removed too, thanks

2020-11-06 15:27 UTC, henriquemoraeszup approved these changes
Im good to go 🚀

2020-11-06 16:15 UTC, victorschumacherzup commented on pkg/formula/tree/checker_test.go
> +			treeChecker.CheckCommands()
Found a way to assert on 6a9be03

2020-11-06 16:49 UTC, brunasilvazup commented on pkg/formula/tree/checker.go
> +}
I know it can be a late improvement, but analyzing the general idea that it is to print only the last duplicate command we could 'optimize' some logic:

 - do what checks for duplicate commands to scroll through the inverted array and stop / return when it finds a duplicate command.

 - So in print we don't need to keep the list of all commands and take the last one by len.

**But** as this idea does not diminish the complexity, it is entirely up to you to change or not.

2020-11-06 16:50 UTC, brunasilvazup approved these changes

2020-11-06 16:55 UTC, victorschumacherzup commented on pkg/formula/tree/checker.go
> +}
Oh nice, but now we are printing the quantity of conflicting commands, if i dont have the full list, it's not gonna be possible to get this info right?

2020-11-06 16:59 UTC, brunasilvazup commented on pkg/formula/tree/checker.go
> +}
Hm no no, this solution is justily the situation with only one command, so follow the game kk.

2020-11-06 18:38 UTC, kaduartur requested changes

2020-11-06 18:38 UTC, kaduartur commented on pkg/cmd/add_repo.go
> +	treeChecker tree.CheckerManager
could you rename `treeChecker` variable to `tree` and `rt` to `tutorial`?

2020-11-06 18:38 UTC, kaduartur commented on pkg/cmd/create_formula.go
> +	treeChecker     tree.CheckerManager
could you rename `treeChecker` variable to `tree` and `rt` to `tutorial`?

2020-11-06 18:38 UTC, kaduartur commented on pkg/formula/tree/checker.go
> +	allCommands := []string{""}
could you declare this variable like this?

```go
	var allCommands []string
```

2020-11-06 18:38 UTC, kaduartur commented on pkg/formula/tree/checker.go
> +	duplicatedCommands := []string{""}
could you declare this variable like this?

```go
	var allCommands []string
```

2020-11-06 18:49 UTC, victorschumacherzup commented
/merge qa

2020-11-06 20:10 UTC, victorschumacherzup commented
/merge qa

2020-11-09 12:33 UTC, victorschumacherzup commented
/merge qa

2020-11-09 12:53 UTC, henriquemoraeszup approved these changes

2020-11-09 14:01 UTC, kaduartur commented
/merge qa

2020-11-09 14:08 UTC, kaduartur approved these changes

2020-11-09 14:08 UTC, merged