add -stdin flag on build formula command
ZupIT/ritchie-cli pull request #648
Opened 2020-10-31 21:44 UTC by aronrichter

### Description
As describe on Issue #615:
Today the `rit build formula` need user interaction, this is a problem to CI integration and general automation.

### Changelog
add `--stdin` flag on build formula command

2020-10-31 22:04 UTC, GuillaumeFalourd commented
Hi @aronrichter, thank you for contributing 👍🏼 

I'll let the CODEOWNERS check everything is ok when they'll be available, and I'll already add the label for your contribution during the #Hacktoberfest! 🚀

2020-11-06 15:09 UTC, henriquemoraeszup approved these changes
Nice job 🚀

2020-11-06 18:52 UTC, victorschumacherzup commented
/merge qa

2020-11-06 19:09 UTC, henriquemoraeszup requested changes
Just found a small correction for cross-platform stability

2020-11-06 19:09 UTC, henriquemoraeszup commented on pkg/cmd/build_formula.go
> +		formulaPath := buildFormulaStdin.WorkspacePath+"/"+buildFormulaStdin.Formula
You need to use `filepath.Join` to support all OSes

2020-11-06 19:19 UTC, victorschumacherzup requested changes

2020-11-06 19:19 UTC, victorschumacherzup commented on pkg/cmd/build_formula.go
> +		formulaPath := buildFormulaStdin.WorkspacePath+"/"+buildFormulaStdin.Formula
this "/" can be a problem with windows, can you use `filepath.Join` ?

2020-11-09 16:06 UTC, henriquemoraeszup approved these changes

2020-11-09 20:01 UTC, victorschumacherzup approved these changes

2020-11-10 17:42 UTC, brunasilvazup commented on pkg/cmd/build_formula.go
> +		if err != nil {
Do you can join this lines in only one with:
`if err := stdin.ReadJson(cmd.InOrStdin(), &buildFormulaStdin); err != nil {`

what do you think?

2020-11-10 17:42 UTC, brunasilvazup commented on pkg/cmd/build_formula.go
> +		if err != nil {
Same suggestion here

2020-11-10 17:47 UTC, brunasilvazup submitted a review, later dismissed

2020-11-13 17:52 UTC, lucasdittrichzup approved these changes

2020-11-13 17:52 UTC, lucasdittrichzup commented
/merge qa

2020-11-13 21:18 UTC, lucasdittrichzup requested changes

2020-11-13 21:18 UTC, lucasdittrichzup commented on pkg/cmd/build_formula.go
> +type buildFormulaStdin struct {
@aronrichter, I did some testing with its implementation and I have two considerations:

1. when I pass the empty `--stdin` flag (`rit build formula --stdin`) the process gets stuck

2. it would be interesting to add the flag on the helper of the command, as it will help anyone who wants to use it

2020-11-19 01:49 UTC, aronrichter commented on pkg/cmd/build_formula.go
> +type buildFormulaStdin struct {
Hey @lucasdittrichzup 

Do you know if this error happen only on this command?
I ask this 'cause I used the same pattern as others commands.
If this problem happen with others commands too, maybe will be a good idea treat this thing on another issue, because will affect every command already developed.

At the mean time, I'll add the flag on helper.

Thank you for the review :grimacing:

2020-11-19 14:22 UTC, brunasilvazup commented on pkg/cmd/build_formula.go
> +type buildFormulaStdin struct {
Hi @aronrichter and @lucasdittrichzup
I checked and this behavior is repeated in other commands too. So do you continue with your current implementation.

I will do other tests in QA, thanks for your contribution (:

2020-11-19 14:42 UTC, brunasilvazup reviewed
Hi @aronrichter,

Can you resolve the latest conflicts, please?

2020-11-20 12:30 UTC, brunasilvazup commented
/merge qa

2020-11-20 12:58 UTC, brunasilvazup commented
Hi @aronrichter,
I create a new formula (`rit teste build-stdin`) in workspace default to tests and tested your implementation with:

```shell
echo '{"workspacePath":"/home/bruna/ritchie-formulas-local", "formula": "rit teste build-stdin"}' | rit build formula --stdin
```
And this returned an error: `Error: formula does not exists`.

I think there may be a problem when searching for the formula on the `buildCommandValidator` on line 262, as it is always looking for a directory that has the complete formula and the formula will be each part a directory.

2020-11-21 01:53 UTC, aronrichter commented
Hi @brunasilvazup ... 

First of all, thank you for your review :grin: 

I was looking at the code, and correct me if I'm wrong, but I understood the rule this way:

When you use the command `rit create formula`, you'll have a dir with the formula's name, and inside of this dir your formula will exist.
The goal of the build formula is take the created formula inside of its dir and just build it;

With that in mind, when you use the prompt option to build a formula, you pass through these steps:
1. select a formula workspace;
2. select a formula or group:
   2.1 select a formula name to Ritchie build it;
   2.2 choose a group, to go down on the file tree, and then select a formula name;

When you select a formula, Ritchie will enter on chosen dir and then build the formula inside using one of those implementations of Build interface:
- local.go
- shell.go 
- docker.go
- make.go
- bat.go

You can see this behavior in `build_formula.go` on line 181 when the program call `if err := b.formula.Build(info); err != nil {`.

When I developed this feature, I tryed to focus on this. 
So, `Workspace` should be the place of your formula's dir, and `Formula` should be the name of your formula, therefore the name of the formula's dir. Keeping the same behavior already implemented on prompt option.

As far I understood of the behavior of Ritchie,  your test is validating a uncreated formula, so would be right you get this error: `Error: formula does not exists`
To validate the "happy path", the test should be something like this:
```
echo '{"workspacePath":"/home/bruna/ritchie-formulas-local", "formula": "name-of-your-formula-already-created"}' | rit build formula --stdin
```

Please forgive me for this large text. It was hard to me explain on less words.
And again, if I understood wrongly the behavior of this feature, I'll fix that, no problem :grimacing: 

Thank you for your time and your patience.

2020-11-23 12:41 UTC, brunasilvazup commented
> Hi @brunasilvazup ...
> 
> First of all, thank you for your review 
> 
> I was looking at the code, and correct me if I'm wrong, but I understood the rule this way:
> 
> When you use the command `rit create formula`, you'll have a dir with the formula's name, and inside of this dir your formula will exist.
> The goal of the build formula is take the created formula inside of its dir and just build it;
> 
> With that in mind, when you use the prompt option to build a formula, you pass through these steps:
> 
> 1. select a formula workspace;
> 2. select a formula or group:
>    2.1 select a formula name to Ritchie build it;
>    2.2 choose a group, to go down on the file tree, and then select a formula name;
> 
> When you select a formula, Ritchie will enter on chosen dir and then build the formula inside using one of those implementations of Build interface:
> 
> * local.go
> * shell.go
> * docker.go
> * make.go
> * bat.go
> 
> You can see this behavior in `build_formula.go` on line 181 when the program call `if err := b.formula.Build(info); err != nil {`.
> 
> When I developed this feature, I tryed to focus on this.
> So, `Workspace` should be the place of your formula's dir, and `Formula` should be the name of your formula, therefore the name of the formula's dir. Keeping the same behavior already implemented on prompt option.
> 
> As far I understood of the behavior of Ritchie, your test is validating a uncreated formula, so would be right you get this error: `Error: formula does not exists`
> To validate the "happy path", the test should be something like this:
> 
> ```
> echo '{"workspacePath":"/home/bruna/ritchie-formulas-local", "formula": "name-of-your-formula-already-created"}' | rit build formula --stdin
> ```
> 
> Please forgive me for this large text. It was hard to me explain on less words.
> And again, if I understood wrongly the behavior of this feature, I'll fix that, no problem 
> 
> Thank you for your time and your patience.

Hi @aronrichter,
Thanks for the explanation and you are correct in your view.
One thing that is incorrect in the development of logic is that the formula is constructed in parts using the directory structure.

> ![image](https://user-images.githubusercontent.com/67295691/99962438-efeef700-2d6e-11eb-95d9-be0b7bc04a8f.png)
> In this example I have a formula `rit test build-stdin`, so I have the `test` directory and inside the` build-stdin` directory.

As you developed it only finds a formula if the directory has its full name, so it only works explicitly for formulas with a single command (rit test).
This logic is in line 263 of the `buildCommandValidator` function.

Were you able to understand the problem?
A test I suggest you do is to create a formula with 2 or 3 commands and build it via stdin.

2020-11-30 12:37 UTC, brunasilvazup commented
Hi @aronrichter, good morning, thanks for the contribution you did a great job and developed a great solution.

Unfortunately we have a new PR (https://github.com/ZupIT/ritchie-cli/pull/692) from the team that will disable the `rit build` command, which is the main change in your PR.
Thus, we will close your PR and the respective issue.

Thank you again for your dedication and if you are interested in contributing to other issues, feel free.

2020-11-30 12:37 UTC, closed without merging