Adding --force-build flag
ZupIT/ritchie-cli pull request #677
Opened 2020-11-16 23:08 UTC by gabriel-pinheiro

Signed-off-by: Gabriel Pinheiro <gabrielctpinheiro@gmail.com>

### Description
You can now run formulas with a `--force-build` (or `-b`) flag that will force it to be built (ok haha) regardless of changes without prompting the user with an extra question

### How to verify it
Run any formula that exists locally in a repository with --force-build or -b and check the build spinner before the execution

### Changelog
Added `--force-build` (or `-b`) flag

![force-build](https://user-images.githubusercontent.com/56726395/99318908-5d6ac700-2847-11eb-8aca-946d641d6afa.gif)

Closes #668

2020-11-17 12:11 UTC, henriquemoraeszup commented on pkg/formula/runner/pre_run_builder.go
> +
I think we need to remove the `bin` folder and the input cache for the build to work properly, can you confirm @kaduartur ?

2020-11-17 15:29 UTC, gabriel-pinheiro commented on pkg/formula/runner/pre_run_builder.go
> +
It looks like the `bin` folder is already being removed in the line below that on b.buildOnWorkspace -> b.builder.Build -> (now on `formula/builder/local.go`, `Build` func) m.buildFormulaBin -> m.dir.Remove (local.go L78)

I'll take a look at how that cache is stored and push a commit with that update, thanks for pointing that out!

2020-11-18 14:34 UTC, kaduartur requested changes

2020-11-18 14:34 UTC, kaduartur commented on pkg/cmd/formula.go
> +		if err := f.formula.Execute(exe, forceBuild); err != nil {
could you create a new field in `formula.ExecuteData` or use the flags field itself to capture the value of` --force-build`?
So you don't break the interface contract.

2020-11-18 14:34 UTC, kaduartur commented on pkg/formula/runner/pre_run_builder.go
> +
I think this should only work for formulas that are in a repository. Because many of the formulas don't have any workspace.

- remove the `/bin` folder
- remove cache files

The Ritchie by default will build the formula because there is no longer a `/bin` folder

2020-11-19 11:17 UTC, gabriel-pinheiro commented on pkg/formula/runner/pre_run_builder.go
> +
Ohh got it! I'll push these changes.

Also, when using the `--force-build`, should Ritchie only rebuild the formula already on `~/.rit/repos` or also override the sources in there from the workspace (if it exists in one)?

2020-11-20 12:14 UTC, GuillaumeFalourd commented on pkg/formula/runner/pre_run_builder.go
> +
I wouldn't override the sources files from `formulas workspaces`. Only the files in the `~/.rit/repos` 🤔 

What scenario do you see where it could be interesting to override the sources files ? (I may be missing something)

2020-11-21 15:10 UTC, gabriel-pinheiro commented on pkg/formula/runner/pre_run_builder.go
> +
Ohh I mean to override the `~/.rit/repos` with the workspace source (instead of only building what's already on `~/.rit/repos`)

2020-11-23 12:51 UTC, GuillaumeFalourd commented on pkg/formula/runner/pre_run_builder.go
> +
Sounds like a good idea to me @gabriel-pinheiro 👍🏼

2020-11-25 12:31 UTC, gabriel-pinheiro commented
I just pushed the changes to build the formula even when it doesn't exist on any workspace (by just deleting the bin dir). I kept the previous code that would update the rit home with the workspace source.

I also pushed the refactor to get the force-build flag from ExecuteData.

I just need to add some more tests (for the new logic) and clear the formula cache in the --force-build and the PR will be ready to approve :)

2020-12-08 13:31 UTC, henriquemoraeszup commented
Wassup @gabriel-pinheiro, is this PR still a draft? I am the release manager this week, if you require any help or have any questions let me know =]

2020-12-09 10:22 UTC, gabriel-pinheiro commented
Hey henrique, I recently got some help from Bruna and Kadu, I'll be able to push the changes now 😄

2021-01-20 21:32 UTC, lucasdittrichzup commented
Hi @gabriel-pinheiro, is this PR still a draft?

2021-02-02 21:01 UTC, brunasilvazup commented
Hi @gabriel-pinheiro, as some time has passed since the beginning of this PR we decided to close it for now.
If you want to continue or stop this PR feel free.

Thank you for your contribution and if you want to talk we are available.

2021-02-02 21:01 UTC, closed without merging