Improvement/help default text
ZupIT/ritchie-cli pull request #689
Opened 2020-11-23 17:11 UTC by victorschumacherzup

### Description

Small change adding a command based text to `help.json`

### How to verify it

Use `rit create formula` and check the `help.json` files.

### Changelog
added a command based text to help.json

2020-11-23 19:20 UTC, brunasilvazup approved these changes

2020-11-24 14:06 UTC, kaduartur requested changes

2020-11-24 14:06 UTC, kaduartur commented on pkg/formula/creator/creator.go
> +			commands += folderName + " "
Why add a space here?

2020-11-24 14:06 UTC, kaduartur commented on pkg/formula/creator/template/default.go
> +    "short": "{{command}}commands",
could you use the Golang `fmt`?

2020-11-24 14:49 UTC, victorschumacherzup commented on pkg/formula/creator/creator.go
> +			commands += folderName + " "
it goes between the commands, without it the command is built like awscreate

2020-11-24 14:51 UTC, victorschumacherzup commented on pkg/formula/creator/template/default.go
> +    "short": "{{command}}commands",
sure!

2020-11-24 17:53 UTC, henriquemoraeszup commented on pkg/formula/creator/template/default.go
> +    "short": "{{command}}formula",
If you already add a space on the template you will be able to  join the commands more elegantly
```suggestion
    "short": "{{command}} formula",
```

2020-11-24 17:53 UTC, henriquemoraeszup commented on pkg/formula/creator/creator.go
> +			commands += folderName + " "
Instead of concatenating with empty space, why not join the `dirs` array?
```
fieldPath := filepath.Join(fields[0:i]...)
commands := strings.Join(fields[0:i], " ")
```

2020-11-24 18:23 UTC, victorschumacherzup commented on pkg/formula/creator/creator.go
>  		if !c.file.Exists(helpPath) {
thanks for recommending this reading
done 11bbf5d7fa3b9e9521978d207408fc6d8e35d3c7

2020-11-24 19:20 UTC, kaduartur approved these changes
LGTM 🥇

2020-11-24 19:29 UTC, victorschumacherzup commented on pkg/formula/creator/template/default.go
> +    "short": "{{command}}formula",
yes! done in a68d9d602086fa25241f8b7ee7ddd9fe28d4e853

2020-11-24 19:30 UTC, victorschumacherzup commented on pkg/formula/creator/creator.go
> +			commands += folderName + " "
changed in a68d9d602086fa25241f8b7ee7ddd9fe28d4e853

2020-11-24 19:41 UTC, henriquemoraeszup requested changes
I think we are missing the tests to check for these files

2020-11-26 16:49 UTC, brunasilvazup submitted a review, later dismissed

2020-11-27 10:42 UTC, henriquemoraeszup commented on pkg/formula/creator/creator_test.go
> +			}
Can you just check for the exact expected test? Also you can apply testify for your assertions

2020-11-30 11:58 UTC, henriquemoraeszup commented on pkg/formula/creator/creator.go
> +		}
you can avoid this unmarshall step by just setting the help properties, like
`help.short = fmt.Sprintf("%s %s", commands, complement)`

2020-11-30 12:03 UTC, henriquemoraeszup commented on pkg/formula/creator/creator_test.go
>  			}
How about making testify standard? Also, this boolean logic seems complex and hard to understand
```suggestion
			if (out.err == nil) {
			      require.NoError(t, got)
			} else {
			     require.NotNil(t, out.err)
			     require.Equal(t, err.Error(), out.err.Error())
			}
```

2020-11-30 12:04 UTC, henriquemoraeszup commented on pkg/formula/creator/creator_test.go
> +				assert.Equal(t, expected, help.Short, errorMsg)
Could you check if a wrong assert is actually failing the test? I think assert only returns a boolean without failing it. `require` seems to do the job better

2020-11-30 12:05 UTC, henriquemoraeszup commented on pkg/formula/creator/template/default.go
>  }`
If you set the properties as suggested above, you will not need this template

2020-11-30 12:22 UTC, victorschumacherzup commented on pkg/formula/creator/creator_test.go
> +				assert.Equal(t, expected, help.Short, errorMsg)
The test fails with an `assert` as well. I really don't know the difference between them

2020-11-30 12:23 UTC, victorschumacherzup commented on pkg/formula/creator/template/default.go
>  }`
yes! thanks

2020-11-30 12:23 UTC, victorschumacherzup commented on pkg/formula/creator/creator_test.go
>  			}
sure! removed

2020-11-30 12:24 UTC, victorschumacherzup commented on pkg/formula/creator/creator.go
> +		}
nice idea! :bulb: 
 thanks

2020-11-30 13:07 UTC, henriquemoraeszup submitted a review, later dismissed
Nice! Just one comment to fix, but I am good to go 🚀

2020-11-30 13:07 UTC, henriquemoraeszup commented on pkg/formula/creator/creator_test.go
> +				require.Equal(t, expected, help.Short, errorMsg)
I think here you wanted to compare with `help.Long`

2020-11-30 13:12 UTC, victorschumacherzup commented on pkg/formula/creator/creator_test.go
> +				require.Equal(t, expected, help.Short, errorMsg)
yes, fixed it on e940471

2020-11-30 13:47 UTC, henriquemoraeszup approved these changes

2020-11-30 14:06 UTC, brunasilvazup approved these changes
:+1:

2020-11-30 17:25 UTC, brunasilvazup commented
/merge qa

2020-11-30 17:28 UTC, merged