Check repository structure
ZupIT/ritchie-cli pull request #705
Opened 2020-12-01 21:28 UTC by matheussn

### Description

I implemented a validation when adding repositories, so that the user can only add repositories that have valid formulas
closes #698

### How to verify it
To validate, you can try to add any repository that is not a Ritchie formula repository, using the `rit add repo` command. The same, should return an error to the user with a message saying that the chosen repository does not have formulas.

### Changelog

Validation in the rit add repo command, to add only formula repositories

2020-12-02 13:59 UTC, kaduartur requested changes

2020-12-02 13:59 UTC, kaduartur commented on pkg/cmd/add_repo.go
> +			if err := ad.repoDeleter.Delete(repository.Name); err != nil {
I think that this logic should be within the "business" layer, more specifically within the Add function.

2020-12-02 13:59 UTC, kaduartur commented on pkg/cmd/add_repo.go
> +			if err := ad.repoDeleter.Delete(r.Name); err != nil {
I think that this logic should be within the "business" layer, more specifically within the Add function.

2020-12-02 13:59 UTC, kaduartur commented on pkg/formula/repo/adder.go
> +		return errors.New("the selected repository has no formulas")
Here you can call the delete repository function and then return the error

2020-12-02 14:22 UTC, matheussn commented on pkg/formula/repo/adder.go
> +		return errors.New("the selected repository has no formulas")
Makes sense!
Could I ignore the `delete` function error?
Or do you think it is better to keep the same rule that is in the `add_repo.go` file?

2020-12-02 17:22 UTC, brunasilvazup commented on pkg/formula/repo/adder.go
> +		return errors.New("the selected repository has no formulas")
At this point in the logic he has already created the repository (line 63), so it is good to delete it here.

Or you can evaluate if we could put this if of the tree first, @kaduartur think this is a good approach?

2020-12-07 12:58 UTC, henriquemoraeszup commented
Hello @matheussn just checking if everything is ok, if you need any support let me know, I'm the designated release manager for this week 😃

2020-12-08 13:24 UTC, kaduartur commented on pkg/formula/repo/adder.go
> +		return errors.New("the selected repository has no formulas")
> Makes sense!
> Could I ignore the `delete` function error?
> Or do you think it is better to keep the same rule that is in the `add_repo.go` file?

good practices in Golang recommend not to ignore errors. [Handle-errors](https://github.com/golang/go/wiki/CodeReviewComments#handle-errors)

2020-12-08 13:27 UTC, kaduartur commented on pkg/formula/repo/adder.go
> +		return errors.New("the selected repository has no formulas")
> At this point in the logic he has already created the repository (line 63), so it is good to delete it here.
> 
> Or you can evaluate if we could put this if of the tree first, @kaduartur think this is a good approach?

when using the delete repository function we have already gained all the functionalities like removing the repo from the repositories.json file.

2020-12-08 13:30 UTC, henriquemoraeszup commented on pkg/formula/repo/adder.go
> +		return errors.New("the selected repository has no formulas")
I think the placement of the delete action makes sense, because to build the tree we **must** have the repo structure in place

2020-12-10 11:18 UTC, henriquemoraeszup approved these changes
I'll be damned, 5 lines of code that generated 257 lines of test. Well done sir 👏

2020-12-10 13:45 UTC, kaduartur commented on pkg/formula/repo/adder.go
> +	deleter formula.RepositoryDeleter
an improvement for the next implementations would be to have a `formula.RepositoryListWriteCreateDeleter` interface, so you can remove the `deleter` field from your structure and directly use the `repo` parameter

2020-12-10 13:45 UTC, kaduartur approved these changes
LGTM!

2020-12-11 18:37 UTC, henriquemoraeszup commented
/merge qa

2020-12-11 18:55 UTC, merged