Delete credential flags
ZupIT/ritchie-cli pull request #774
Opened 2020-12-14 11:28 UTC by henriquemoraeszup

### Description

Added flag capacity on delete credential

### How to verify it
Run the command `rit delete credential --provider=<your provider>`

### Changelog

Added flag capacity to `rit delete credential`

2020-12-14 17:18 UTC, brunasilvazup commented on pkg/cmd/delete_credential.go
> +	cred, err := d.List("Credentials: ", providers)
This name of variable could be change `provider` to equal in line 130?

2020-12-14 17:24 UTC, brunasilvazup approved these changes

2020-12-15 16:30 UTC, brunasilvazup commented on pkg/cmd/delete_credential.go
> +	}
This `else` is not necessary, right?
```go
} else {
		return d.resolvePrompt(context)
}
```
->
```go
}
return d.resolvePrompt(context)
```

2020-12-15 16:45 UTC, brunasilvazup approved these changes

2020-12-15 18:51 UTC, kaduartur requested changes

2020-12-15 18:51 UTC, kaduartur commented on pkg/cmd/cmd.go
> +	return cmd.Flags().NFlag() > 0
When you use the `--help` flag, does it work?

2020-12-15 18:51 UTC, kaduartur commented on pkg/cmd/delete_credential.go
> +	providerFlagName        = "provider"
could you extract the `flag` struct from the formula.go and use `addReservedFlags` function to generate all flags to any commands?

2020-12-15 18:51 UTC, kaduartur commented on pkg/cmd/delete_credential.go
> +		} else if inputParams.provider == "" {
I think you should return an error when the user sends an empty provider, so you don't need to check if the provider is empty here.

2020-12-15 18:51 UTC, kaduartur commented on pkg/cmd/delete_credential.go
> +	return inputConfig{provider}, nil
you should return an error if the provider is empty

2020-12-19 17:07 UTC, henriquemoraeszup commented on pkg/cmd/cmd.go
> +	return cmd.Flags().NFlag() > 0
good point, but it works as intended, seems like `help` is a cobra reserved flag that gets priority when called

2020-12-19 17:34 UTC, henriquemoraeszup commented on pkg/cmd/delete_credential.go
> +	providerFlagName        = "provider"
Sorry I am a bit lost, are core commands supposed to have reserved flags?

2020-12-19 19:33 UTC, henriquemoraeszup commented on pkg/cmd/delete_credential.go
> +		} else if inputParams.provider == "" {
Returning the error makes sense, but we cannot neglect this case. This happens when we prompt the user if she really wants to delete and she says no

2020-12-22 21:10 UTC, kaduartur requested changes

2020-12-22 21:10 UTC, kaduartur commented on pkg/cmd/delete_credential.go
> +	flags.String(providerFlagName, "", providerFlagDescription)
- I think that you can use the `flag` struct to represent a flag.
https://github.com/ZupIT/ritchie-cli/blob/84b00081d6ffcb6177852478051d090468891eb8/pkg/cmd/formula.go#L78
 
- you can use this function to create your flags.
https://github.com/ZupIT/ritchie-cli/blob/84b00081d6ffcb6177852478051d090468891eb8/pkg/cmd/formula.go#L227

- here we have an example of how to use it:
https://github.com/ZupIT/ritchie-cli/blob/84b00081d6ffcb6177852478051d090468891eb8/pkg/cmd/formula.go#L47

you can extract this function and struct to [cmd.go](https://github.com/ZupIT/ritchie-cli/blob/master/pkg/cmd/cmd.go) file

2020-12-23 11:08 UTC, henriquemoraeszup commented on pkg/cmd/delete_credential.go
> +	flags.String(providerFlagName, "", providerFlagDescription)
now I see...

2021-01-04 13:10 UTC, brunasilvazup approved these changes

2021-01-04 18:40 UTC, kaduartur approved these changes
Good job 🚀

2021-01-04 18:41 UTC, kaduartur commented
/merge qa

2021-01-04 22:03 UTC, kaduartur requested changes

2021-01-04 22:03 UTC, kaduartur commented on pkg/cmd/delete_credential.go
> +	providers := make([]string, len(data))
When you declare an array like this, you are saying that its capacity is the date size and you are giving each position of the array an empty value, by appending it will add to the next position displaying to the user a select with empty fields.

![image](https://user-images.githubusercontent.com/17505818/103583960-73981980-4ebf-11eb-8bfc-7396e810e2c4.png)


For example, if the date has a size of 3 you will have an array with size 3, and when appending it will add one more position and the size of your array will be 6 with the first 3 empty positions.

we have two ways to fix this:
``` go

var providers []string // Simpler

providers := make([]string, 0, len(data)) // More complex
```

2021-01-07 13:33 UTC, henriquemoraeszup commented on pkg/cmd/delete_credential.go
> +	providers := make([]string, len(data))
the first option does not pass the linter since we need to preallocate it, going for the second

2021-01-08 19:03 UTC, kaduartur approved these changes

2021-01-08 19:04 UTC, kaduartur commented
/merge qa

2021-01-11 11:56 UTC, merged