Tests on slice
ZupIT/ritchie-cli pull request #808
Opened 2020-12-19 21:17 UTC by henriquemoraeszup

### Description

There were some changes on this PR besides adding testify. Some of the methods from the utils package were used in a single file. Such methods were moved to their respective files. Also to avoid folder nesting, `slice_util.go` was moved up one folder

### How to verify it
Run slice tests and check if they pass

### Changelog

Test refactor on slice util

2020-12-22 14:37 UTC, brunasilvazup approved these changes

2020-12-22 20:53 UTC, kaduartur requested changes
Keep the `sliceutil/` package inside the `slice/` so we don't have **"util"** packages lost inside `pkg/`, this is a very common pattern in Golang. An example is the [ioutil](https://golang.org/pkg/io/ioutil) package.

2020-12-23 15:42 UTC, kaduartur approved these changes
I liked the approach of removing functions that are specific to their respective packages! 🚀

2020-12-23 15:42 UTC, kaduartur commented
/merge qa

2020-12-23 15:51 UTC, merged