created rit add workspace command
ZupIT/ritchie-cli pull request #809
Opened 2020-12-19 21:58 UTC by aronrichter

### Description
As requested on #802, is necessary a command do add a new workspace.

### How to verify it
You can run the command `rit add workspace` and after you can run `rit list workspace` and then you can see your workspace added

### Changelog
Added a new core command `rit add workspace`

2020-12-19 22:04 UTC, henriquemoraeszup reviewed
Thanks for your contribution aron! Just a couple of points below, keep it up 💪

2020-12-19 22:04 UTC, henriquemoraeszup commented on pkg/cmd/add_workspace.go
> +
Hey! we just started adding support for flags on core commands, can you add here as well? you can check #774 for a reference =]

2020-12-19 22:04 UTC, henriquemoraeszup commented on pkg/cmd/add_workspace_test.go
> +			}
Can you use testify assertions and mocks here? We are adopting a new lib to make our tests clearer. You can find an example here
https://github.com/ZupIT/ritchie-cli/pull/774/files#diff-d694f418a29ad6844afed8da9f20f717d0d953966216b43c3e1155d409f08779R363

2020-12-20 13:50 UTC, henriquemoraeszup commented on pkg/cmd/add_workspace.go
> +	}
I think we should return an error if the user has any flags but forgets to fill them instead of falling back to prompt

2020-12-20 13:54 UTC, henriquemoraeszup commented on pkg/cmd/add_workspace.go
> +func (a addWorkspaceCmd) runPrompt() CommandRunnerFunc {
nitpick: you can change the method name to something more semantic like `runFormula` because we are not necessarily running a prompt now

2020-12-20 13:55 UTC, henriquemoraeszup commented on pkg/cmd/add_workspace_test.go
> +		{
can we have an error case for a user that only adds one flag?

2020-12-21 11:37 UTC, henriquemoraeszup commented on pkg/cmd/add_workspace.go
> +	}
what happens if you do `rit add workspace --name= --path=`?

2020-12-21 12:06 UTC, henriquemoraeszup commented on pkg/cmd/add_workspace_test.go
> +			name:                  "add new workspace by prompt",
One detail, on a success case, you want to check if the workspace entry was actually added to `~/.rit/formula_workspaces.json` so maybe you do not want to mock the workspace added

2020-12-21 13:10 UTC, aronrichter commented on pkg/cmd/add_workspace.go
> +	}
It was the same thing when you don't pass any flag.
But, I understood why you'd ask, so I changed to check the number of flags passed before I decided what to do.

2020-12-21 13:12 UTC, aronrichter commented on pkg/cmd/add_workspace_test.go
> +			name:                  "add new workspace by prompt",
I'm not sure if I wanted to check that. 
My unit it's until I called the method `a.workspace.Add(wspace)` after that the behavior ins't responsability of this method. Because of this I mocked my test. 
What do you think?!

2020-12-21 17:59 UTC, henriquemoraeszup commented on pkg/cmd/add_workspace_test.go
> +			name:                  "add new workspace by prompt",
I do agree with you, lately we have been trying to adopt a more functional-like approach on our tests. But your argument is good as well, if you intend to continue with the mock, then maybe it is best to test that it has been called with the right arguments to ensure a thorough test. Check out assertCalled
https://godoc.org/github.com/stretchr/testify/mock#Mock.AssertCalled

2020-12-21 18:02 UTC, henriquemoraeszup reviewed
Just one last suggestion on the mock but I am good to go. Just not approving now because any further commit would dismiss my review

2020-12-21 21:13 UTC, aronrichter commented on pkg/cmd/add_workspace_test.go
> +			name:                  "add new workspace by prompt",
That's right, I can mock my test, but at least a need to guarantee I'm passing the right parameters.
Thanks for the observation! 😄

2020-12-21 23:27 UTC, henriquemoraeszup commented on pkg/cmd/add_workspace_test.go
> +			workspaceMock.On("Add", wspace).Return(tt.addWorkspaceWithError)
nice, this is even better than what I suggested 😄 will be recommending this to the team

2020-12-21 23:36 UTC, henriquemoraeszup approved these changes
👏 👏 👏 👏 
![giphy (12)](https://user-images.githubusercontent.com/68074718/102832079-2e0e2380-43cc-11eb-80a3-3a236b2c2835.gif)

2020-12-22 21:22 UTC, kaduartur requested changes
Good job 🚀 

You just needed to add this command to the core command list, you can add it in the [api.go](https://github.com/ZupIT/ritchie-cli/blob/master/pkg/api/api.go) file. we use this to generate our autocomplete of the core commands.

2020-12-22 21:22 UTC, kaduartur commented on pkg/cmd/add_workspace.go
> +	inText    prompt.InputText
could you rename this to `input` to make it more readable?

2020-12-22 21:22 UTC, kaduartur commented on pkg/cmd/add_workspace.go
> +		if count := cmd.Flags().NFlag(); count == 0 {
could you simplify it to `cmd.Flags().NFlag() == 0`?

2020-12-23 15:44 UTC, kaduartur approved these changes
LGTM 🥇

2020-12-23 15:44 UTC, kaduartur commented
/merge qa

2020-12-23 15:53 UTC, kaduartur commented
/merge qa

2020-12-23 16:34 UTC, merged