Feature - input autocomplete
ZupIT/ritchie-cli pull request #821
Opened 2021-01-07 18:26 UTC by JoaoDanielRufino

### Description
Added input autocomplete(https://github.com/JoaoDanielRufino/go-input-autocomplete) to all workspaces input. Also, I added the option **type path** on config.json to include this input

### How to verify it
Run any formula with **type path** on config.json or any command that requires the user to enter the path to their workspaces. Hit **tab key** to autocomplete the path.

### Changelog
Input Autocomplete

2021-01-13 18:23 UTC, kaduartur approved these changes
LGTM 🚀

2021-01-14 14:14 UTC, henriquemoraeszup requested changes
Nice! just a couple of comments

2021-01-14 14:14 UTC, henriquemoraeszup commented on pkg/cmd/add_workspace_test.go
> +			// textMock.On("Text", "Enter the path of workspace (e.g.: /home/user/github) ", true, mock.Anything).Return(tt.workspacePath, nil)
commented code

2021-01-14 14:14 UTC, henriquemoraeszup commented on pkg/formula/input/prompt/prompt_test.go
> +}
We should use testify mocks

2021-01-14 14:14 UTC, henriquemoraeszup commented on pkg/formula/runner/docker/runner_test.go
> +}
we should strive to use testify mocks

2021-01-14 14:14 UTC, henriquemoraeszup commented on pkg/formula/runner/local/runner_test.go
> +}
same here

2021-01-15 12:58 UTC, brunasilvazup commented on pkg/cmd/mocks_test.go
> +
You can only use testify mocks in package mocks. We are changing all simulations for this.

2021-01-15 13:39 UTC, brunasilvazup commented on pkg/formula/input/prompt/prompt_test.go
> +			inPath := InputPathMock{}
I was expecting specific tests for your new entry - entry path (similar to the testing functions in this file 'TestInputManager_Multiselect').
Could you add a function to test this?

2021-01-15 14:26 UTC, brunasilvazup requested changes

2021-01-20 21:31 UTC, lucasdittrichzup approved these changes

2021-01-21 19:10 UTC, brunasilvazup approved these changes

2021-01-26 17:54 UTC, henriquemoraeszup commented
Hey @joaorufinozup, can you update the description with code example of how to use on the `config.json` for documentation purposes please?

2021-01-26 21:38 UTC, lucasdittrichzup commented
/merge qa

2021-01-29 21:16 UTC, brunasilvazup commented
Hi @JoaoDanielRufino,
During the quality control tests in Windows, we identified some bugs with the command `rit add workspace`, we came to the conclusion that it was due to changes in your PR, we will do more tests next week.

That was the reason why your PR did not come out in the last release, if you want to do this test we would also be grateful.

In the meantime I will leave PR out of the way for review and with a wait.

2021-02-26 14:25 UTC, henriquemoraeszup commented
/merge qa

2021-03-04 10:37 UTC, henriquemoraeszup commented
/merge qa

2021-03-04 10:39 UTC, henriquemoraeszup commented
/merge qa

2021-03-04 11:10 UTC, henriquemoraeszup requested changes
When you run `--help` the flag of a path input is not mapping. It is also recommended to autofill just enough for the common option, not just pick the first one. Example
```
ls
ritchie-cli    ritchie-henrique
```
if I type `r` then `tab` it should fill up to `ritchie-`

2021-03-05 14:42 UTC, joaorufinozup commented
> When you run `--help` the flag of a path input is not mapping. It is also recommended to autofill just enough for the common option, not just pick the first one. Example
> 
> ```
> ls
> ritchie-cli    ritchie-henrique
> ```
> 
> if I type `r` then `tab` it should fill up to `ritchie-`

The `--help`flag is working now

2021-03-05 18:44 UTC, henriquemoraeszup commented
/merge qa

2021-03-08 13:31 UTC, henriquemoraeszup commented
/merge qa

2021-03-09 17:30 UTC, henriquemoraeszup approved these changes

2021-03-09 17:30 UTC, merged