Fix/print error messages in pre builder
ZupIT/ritchie-cli pull request #829
Opened 2021-01-15 20:38 UTC by brunasilvazup

### Description

### How to verify it

### Changelog

2021-01-19 19:52 UTC, henriquemoraeszup commented on internal/mocks/mocks.go
> +}
Can you move this to a dedicated file in `mocks` with the package name? The `mocks.go` file is getting large already

2021-01-19 19:52 UTC, henriquemoraeszup commented on pkg/formula/runner/pre_run_builder_test.go
>  type workspaceListHasherMock struct {
should we strive to eliminate this guy?

2021-01-19 21:40 UTC, kaduartur requested changes

2021-01-19 21:40 UTC, kaduartur commented on pkg/formula/runner/pre_run_builder.go
>  func (b PreRunBuilderManager) Build(relativePath string) {
I think you could return an error in this method, it will make your tests easier.

2021-01-19 21:40 UTC, kaduartur commented on pkg/formula/runner/pre_run_builder.go
> +		fmt.Println(prompt.Red(msg))
Here it makes sense for you to return the error, so you prevent its repetition for the user.

2021-01-22 17:49 UTC, brunasilvazup commented on pkg/formula/runner/pre_run_builder.go
> +		fmt.Println(prompt.Red(msg))
I will be change this method to return error.

2021-01-26 18:34 UTC, lucasdittrichzup submitted a review, later dismissed

2021-01-26 18:36 UTC, henriquemoraeszup submitted a review, later dismissed
Nice, just a single comment

2021-01-26 18:36 UTC, henriquemoraeszup commented on pkg/cmd/add_repo.go
> +		sort.Strings(providers)
can you move the sort to inside the `ar.repoProviders.List()` method? It should not be the responsibility of this command to know that. Also, this way we only need to edit a single point in code, other packages invoking this method could stumble upon the same problem

2021-01-26 18:40 UTC, henriquemoraeszup commented
Can you add this PR to the pre run test here?
https://github.com/ZupIT/ritchie-cli/issues/788

2021-01-26 18:49 UTC, brunasilvazup commented on pkg/cmd/add_repo.go
> +		sort.Strings(providers)
Yes, I can change, you're right.

2021-01-26 19:17 UTC, lucasdittrichzup submitted a review, later dismissed

2021-01-26 20:49 UTC, brunasilvazup commented
/merge qa

2021-02-05 13:39 UTC, brunasilvazup commented
/merge qa

2021-02-08 16:57 UTC, kaduartur approved these changes
LGTM 🚀

2021-02-08 17:17 UTC, merged