Feature/add repo token
ZupIT/ritchie-cli pull request #833
Opened 2021-01-22 12:02 UTC by matheussn

### Description

Now the command `rit add repo` has a specific credential, so that the user does not need to regenerate his private tokens each time the command is executed.

### How to verify it
In its first execution, when adding a private repository, the command will request the token, as it already did. However, the command now saves this token in a credential.
After executing the `rit add repo` command adding a new private repository, use the `rit list credential` command, to verify that a new credential has been created in the current environment.

### Changelog

Save and reuse repo credentials for private repos

2021-01-22 12:03 UTC, matheussn commented on pkg/cmd/add_repo.go
> +			token, err = ad.Resolve("CREDENTIAL_" + provider + "-add-repo_token")
I didn't really like this implementation, but I'm afraid to try a more "beautiful" implementation and end up getting more complex than necessary.

I accept suggestions.

2021-01-26 15:21 UTC, henriquemoraeszup commented
Hey, we had a recent merge that affects add repo, can you update it?

2021-01-26 17:22 UTC, henriquemoraeszup commented on pkg/cmd/add_repo.go
> +			token, err = ad.Resolve("CREDENTIAL_" + provider + "-add-repo_token")
I think reusing the resolver is the way to go, if anything changes on the logic, we still have one source of truth.

2021-01-26 17:22 UTC, henriquemoraeszup commented on pkg/cmd/add_repo.go
> +			token, err = ad.Resolve("CREDENTIAL_" + provider + "-add-repo_token")
On another note, it is convention to use credential constants always capitalized, like `CREDENTIAL_GITHUB_ADD_REPO_TOKEN`

2021-01-26 17:22 UTC, henriquemoraeszup commented on pkg/cmd/add_repo.go
> +					"Or move to a new environment with command:\n"+
Nitpick:
```suggestion
					"Or switch to a new environment with the command:\n"+
```

2021-01-26 17:22 UTC, henriquemoraeszup commented on pkg/credential/settings.go
> +		"gitlab-add-repo": []Field{token},
This is a "reserved" credential, not sure we should expose to the user, what do you think? Can we edit credentials in Ritchie after it has been set?

2021-01-26 22:32 UTC, matheussn commented on pkg/credential/settings.go
> +		"gitlab-add-repo": []Field{token},
I think it makes sense to keep them "reserved"

2021-01-27 16:54 UTC, brunasilvazup commented
> ### Description
> Now the command `rit add repo` has a specific credential, so that the user does not need to regenerate his private tokens each time the command is executed.
> 
> ### How to verify it
> In its first execution, when adding a private repository, the command will request the token, as it already did. However, the command now saves this token in a credential.
> After executing the `rit add repo` command adding a new private repository, use the `rit list credential` command, to verify that a new credential has been created in the current environment.
> 
> ### Changelog
> Save and reuse repo credentials for private repos

Hi @matheussn, could you add gifs with the simulation of your change operation please?

2021-01-27 20:28 UTC, kaduartur requested changes

2021-01-27 20:28 UTC, kaduartur commented on pkg/cmd/add_repo.go
> +			errorString := fmt.Sprintf("permission error:\nYou must overwrite the current token (%s-add-repo) with command:\n"+
could you extract `errorString` to const and create it using the raw string literals **``**?

2021-01-27 20:28 UTC, kaduartur commented on pkg/cmd/add_repo.go
> +		if strings.Contains(err.Error(), "401") {
I think you can create a specific error for 401 Unauthorized and check if err is equal

2021-04-22 20:07 UTC, lucasdittrichzup commented
what's up @matheussn? hope you're well! if you have any questions to adjust the PR according to the team's suggestions, just get in touch with us, okay?

2021-07-01 18:36 UTC, GuillaumeFalourd commented
Giving continuity to the feature implementation here: https://github.com/ZupIT/ritchie-cli/pull/986

2021-07-01 18:36 UTC, closed without merging