Create translation for init command
ZupIT/ritchie-cli pull request #834
Opened 2021-01-22 19:45 UTC by kaduartur

### Description
Create translation to init command

### How to verify it
It's a small part of the #775 issue, a separate pull request was created to facilitate code review

2021-01-22 22:45 UTC, lucasdittrichzup approved these changes

2021-01-26 13:42 UTC, brunasilvazup commented on pkg/formula/repo/priority_setter_test.go
> -type fileWriteReadExisterMockOnSucessReadData struct{}
These tests in that file are no longer used?

2021-01-26 13:42 UTC, brunasilvazup commented on pkg/cmd/mocks_test.go
> -type inputTextValidatorMock struct{}
These tests in that file are no longer used?

2021-01-26 14:14 UTC, brunasilvazup approved these changes
I left two comments, but I think it's just an update from the master, other than that it's ok

2021-01-26 14:22 UTC, henriquemoraeszup requested changes

2021-01-26 14:22 UTC, henriquemoraeszup commented on internal/pkg/i18n/i18n.go
> +	}
awesome 🥳

2021-01-26 14:22 UTC, henriquemoraeszup commented on internal/pkg/i18n/i18n_test.go
> +			name: "use default language when message not found for current lang",
should we have a windows test? Can we emulate it?

2021-01-26 14:22 UTC, henriquemoraeszup commented on internal/pkg/i18n/translations.go
> +var _resourcesI18nEnToml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x8c\x56\x51\x8b\x14\x49\x12\x7e\xf7\x57\x84\x03\xc7\xdd\x41\x5b\xfd\x3e\x70\xc8\x70\x7a\x77\x03\x3a\xca\x38\x22\x9e\x25\x12
Can you add a comment on what is this for?

2021-01-26 14:22 UTC, henriquemoraeszup commented on internal/pkg/i18n/translations.go
> +var _resourcesI18nPt_brToml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x8a\xce\xcc\xcb\x2c\xd1\x4b\xce\x4d\xd1\x4b\x49\x2d\x4e\x2e\xca\x2c\x28\xc9\xcc\xcf\x8b\xe5\xca\x2f\xc9\x48\x2d\x52\xb0\
can you add a comment on what is this for?

2021-01-26 14:22 UTC, henriquemoraeszup commented on internal/pkg/i18n/translations.go
> +	info := bindataFileInfo{name: "resources/i18n/en.toml", size: 3559, mode: os.FileMode(420), modTime: time.Unix(1611341256, 0)}
Can we avoid magic numbers, especially for the unix timestamp?

2021-01-26 14:22 UTC, henriquemoraeszup commented on internal/pkg/i18n/translations.go
> +	info := bindataFileInfo{name: "resources/i18n/pt_BR.toml", size: 70, mode: os.FileMode(420), modTime: time.Unix(1611239673, 0)}
We can try to avoid magic numbers

2021-01-26 18:03 UTC, kaduartur commented on pkg/formula/repo/priority_setter_test.go
> -type fileWriteReadExisterMockOnSucessReadData struct{}
was removed because it was not being used, the lint started to break.

2021-01-26 18:03 UTC, kaduartur commented on pkg/cmd/mocks_test.go
> -type inputTextValidatorMock struct{}
was removed because it was not being used, the lint started to break.

2021-01-26 18:08 UTC, kaduartur commented on internal/pkg/i18n/i18n.go
> +	}
this file is automatically generated by go-bindata

2021-01-26 18:08 UTC, kaduartur commented on internal/pkg/i18n/translations.go
> +var _resourcesI18nEnToml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x8c\x56\x51\x8b\x14\x49\x12\x7e\xf7\x57\x84\x03\xc7\xdd\x41\x5b\xfd\x3e\x70\xc8\x70\x7a\x77\x03\x3a\xca\x38\x22\x9e\x25\x12
this file is automatically generated by go-bindata

2021-01-26 18:08 UTC, kaduartur commented on internal/pkg/i18n/translations.go
> +var _resourcesI18nPt_brToml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x8a\xce\xcc\xcb\x2c\xd1\x4b\xce\x4d\xd1\x4b\x49\x2d\x4e\x2e\xca\x2c\x28\xc9\xcc\xcf\x8b\xe5\xca\x2f\xc9\x48\x2d\x52\xb0\
this file is automatically generated by go-bindata

2021-01-26 18:09 UTC, kaduartur commented on internal/pkg/i18n/translations.go
> +	info := bindataFileInfo{name: "resources/i18n/en.toml", size: 3559, mode: os.FileMode(420), modTime: time.Unix(1611341256, 0)}
this file is automatically generated by go-bindata

2021-01-26 18:09 UTC, kaduartur commented on internal/pkg/i18n/translations.go
> +	info := bindataFileInfo{name: "resources/i18n/pt_BR.toml", size: 70, mode: os.FileMode(420), modTime: time.Unix(1611239673, 0)}
this file is automatically generated by go-bindata

2021-01-26 18:13 UTC, kaduartur commented on internal/pkg/i18n/i18n_test.go
> +			name: "use default language when message not found for current lang",
we are unable to mock the constant `runtime.GOOS`, just in the specific operational systems.

2021-02-03 14:18 UTC, henriquemoraeszup approved these changes

2021-02-03 14:20 UTC, merged