Set formula runner flags
ZupIT/ritchie-cli pull request #836
Opened 2021-01-26 23:38 UTC by henriquemoraeszup

### Description

* Adding flag capacity to `rit set formula-runner`
* Removed file manager dependency on the config runner
* Refactoring tests on the config runner (contributes to #788)
* Refactored tests on the formula runner command (Contributes to #776)

### How to verify it
Run a flag command with `rit set formula-runner --runner=docker`

### Changelog

Added flag support for rit set formula-runner

2021-01-27 13:32 UTC, brunasilvazup commented on pkg/cmd/set_formula_runner_test.go
> +	assert.NoError(t, err)
I think this error checking is unnecessary, in line 91 it's not checked and it is also a small part of the test construction.
What do you think?

2021-01-27 13:33 UTC, brunasilvazup commented on pkg/cmd/set_formula_runner_test.go
> +	assert.NoError(t, err)
I think this error checking is unnecessary, in line 91 it's not checked and it is also a small part of the test construction.
What do you think?

2021-01-27 13:33 UTC, brunasilvazup commented on pkg/cmd/set_formula_runner_test.go
> +				assert.FileExists(t, runnerFile)
Do you can check the value in runnerFile too?

2021-01-27 13:34 UTC, brunasilvazup commented on pkg/cmd/set_formula_runner_test.go
> +			cmd.PersistentFlags().Bool("stdin", tt.inputStdin != "", "input by stdin")
:1st_place_medal:

2021-01-27 13:35 UTC, brunasilvazup commented on pkg/cmd/set_formula_runner_test.go
> +			_ = os.Remove(runnerFile)
This is necessary?

2021-01-27 14:27 UTC, henriquemoraeszup commented on pkg/cmd/set_formula_runner_test.go
> +	assert.NoError(t, err)
Sounds good. Actually, it could break if we actually had this folder already. Even with an error, it is better to ignore it

2021-01-27 14:30 UTC, henriquemoraeszup commented on pkg/cmd/set_formula_runner_test.go
> +			_ = os.Remove(runnerFile)
Yes, since we are creating the file on success runs, we want to ensure it is not there in the first place. Otherwise, a second success could lead to a false positive since the file was already created by a previous test

2021-01-29 20:41 UTC, brunasilvazup submitted a review, later dismissed

2021-02-01 14:33 UTC, lucasdittrichzup approved these changes

2021-02-01 17:50 UTC, kaduartur requested changes

2021-02-01 17:50 UTC, kaduartur commented on pkg/cmd/set_formula_runner.go
> +		description: "runner name (local or docker)",
Could you use `formula.RunnerTypes` to show the available run types?

2021-02-02 18:39 UTC, kaduartur approved these changes
LGTM 🚀

2021-02-02 21:04 UTC, brunasilvazup approved these changes
LGTM

2021-02-03 14:19 UTC, lucasdittrichzup approved these changes

2021-02-08 16:39 UTC, brunasilvazup commented
QA tests on linux and windows are OK.

2021-02-08 16:39 UTC, merged