fix: required multiselect
ZupIT/ritchie-cli pull request #842
Opened 2021-01-28 20:43 UTC by lucasdittrichzup

### Description
The adoption team found a bug in the multiselect input when the required field is not sent.

To solve this, a validation was added that checks if the field is sent before being used in the code.

Close #839

### How to verify it
1. clone this PR (**`git fetch origin pull / 842 / head: fix/required-multiselect`**)
2. create a formula with **multiselect input** _without_ the **required field**
3. run the formula and verify that the error no longer occurs

### Changelog
Add validation in case the required field is not sent in the multiselect input

2021-01-29 11:30 UTC, henriquemoraeszup submitted a review, later dismissed

2021-01-29 18:50 UTC, brunasilvazup approved these changes

2021-02-01 16:29 UTC, kaduartur requested changes

2021-02-01 16:29 UTC, kaduartur commented on pkg/prompt/multiselect.go
> +	fInput "github.com/ZupIT/ritchie-cli/pkg/formula/input"
I think that you don't need to use an alias in this case.

2021-02-01 21:52 UTC, lucasdittrichzup commented on pkg/prompt/multiselect.go
> +	fInput "github.com/ZupIT/ritchie-cli/pkg/formula/input"
I used the alias because the name of the package is input and since I already use that name, there is conflict and the build breaks. Do you have any suggestions on how to resolve this?

2021-02-02 18:27 UTC, henriquemoraeszup commented on pkg/prompt/multiselect.go
> +	fInput "github.com/ZupIT/ritchie-cli/pkg/formula/input"
I think alias is fine, its either this or rename your `input` variable

2021-02-02 19:59 UTC, lucasdittrichzup commented on pkg/prompt/multiselect.go
> +	fInput "github.com/ZupIT/ritchie-cli/pkg/formula/input"
for now, I decided to rename the variable

2021-02-04 19:14 UTC, brunasilvazup approved these changes

2021-02-05 14:21 UTC, kaduartur approved these changes

2021-02-05 14:27 UTC, henriquemoraeszup approved these changes
This will conflict with #843

2021-02-08 16:43 UTC, merged