Support for list input type
ZupIT/ritchie-cli pull request #843
Opened 2021-01-28 22:20 UTC by henriquemoraeszup

### Description

An excuse to refactor `package prompt` tests. Some of the implementations in this PR
* Support for `list` type in the `config.json` file
* Removed mocks from the test file
* Test refactor of the 900+ lines of code to comply with the new implementation method
* Removed `fileManager` dependency from `prompt`
* Tests actually check if envs were created
* Removed non dynamic entries from table tests
* Removed table test from `Default` test, since it only had a single test

### How to verify it
Run a formula with the config `"type": "list"`, it should work normally

### Changelog

Support for list input type

2021-02-04 21:33 UTC, brunasilvazup submitted a review, later dismissed

2021-02-05 14:44 UTC, kaduartur requested changes

2021-02-05 14:44 UTC, kaduartur commented on pkg/formula/input/prompt/prompt.go
> +			fmt.Sprintln("Write cache error")
Could you use `fmt.Println("Write cache error")`?

2021-02-05 14:44 UTC, kaduartur commented on pkg/formula/input/prompt/prompt.go
>  	if input.Cache.Active {
Could you simplify this function as suggested below?

```suggestion
	if !input.Cache.Active {
		return input.Items, nil
	}
	 
	cachePath := fmt.Sprintf(CachePattern, formulaPath, strings.ToUpper(input.Name))
	fileBytes, err := ioutil.ReadFile(cachePath)
	if err != nil {
		itemsBytes, err := json.Marshal(input.Items)
		if err != nil {
			return nil, err
		}
	
		if err = ioutil.WriteFile(cachePath, itemsBytes, os.ModePerm); err != nil {
			return nil, err
		}
		
		return input.Items, nil
	}
		
	var items []string
	if err := json.Unmarshal(fileBytes, &items); err != nil {
		return nil, err
	}

	return items, nil
```

2021-02-05 18:10 UTC, kaduartur approved these changes

2021-02-05 20:28 UTC, brunasilvazup approved these changes

2021-02-08 16:49 UTC, merged