Tutorial flags
ZupIT/ritchie-cli pull request #846
Opened 2021-02-02 18:20 UTC by henriquemoraeszup

### Description

* Adding flag support to `rit tutorial` command (closes #715 )
* Removing file manager dependencies on rtutorial package
* Refactoring `rtutorial` tests (closes #795 )
* Refactoring tests for cmd/tutorial command (contributes to #776 )

### How to verify it
You can run `rit tutorial --enabled=false` and check that the tutorial has been disabled

### Changelog

Added flag support for rit tutorial command

2021-02-02 21:54 UTC, brunasilvazup submitted a review, later dismissed
LGTM :1st_place_medal:

2021-02-09 13:35 UTC, lucasdittrichzup submitted a review, later dismissed

2021-02-09 15:01 UTC, kaduartur requested changes

2021-02-09 15:01 UTC, kaduartur commented on pkg/rtutorial/finder.go
>  		tutorialFile: fmt.Sprintf(TutorialPath, homePath),
Could you use `filepath.Join()` to format the tutorial path?

2021-02-09 15:01 UTC, kaduartur commented on pkg/rtutorial/setter.go
>  		tutorialFile: fmt.Sprintf(TutorialPath, homePath),
Could you use `filepath.Join()` to format the tutorial path?

2021-02-09 16:54 UTC, kaduartur approved these changes
LGTM 🚀

2021-02-09 17:11 UTC, brunasilvazup approved these changes

2021-02-09 18:34 UTC, lucasdittrichzup approved these changes

2021-02-09 19:27 UTC, merged