Internationalization Ritchie-cli
ZupIT/ritchie-cli pull request #847
Opened 2021-02-03 15:12 UTC by kaduartur

### Description
This pull request implements the internationalization of Ritchie-cli:

- We created a new package called i18n which contains the translation solver by ID and a file called `translations.go` which is automatically generated by the `make generate-translation` command, it is worth remembering that when updating the translation files in `resource/i18n` we should always run this command.

- We centralize the Richie-cli configurations in one place, the file responsible for writing and reading these configs is at `/internal/pkg/config/config.go`. The new config file is created at `˜/.rit/configs.toml`.

- Improved the user experience in the `rit init` command, already using the Ritchie translation part.
Here is a demonstration of the git init command:

![rit init](https://user-images.githubusercontent.com/17505818/106766704-dee91e80-6618-11eb-90f6-5fa96b1bf7d4.gif)

### How to verify it
When executing any Ritchie command it should behave like the latest versions, only the `rit init` command that has had visual modifications.

### Changelog
Internationalization Ritchie-cli

2021-02-04 20:26 UTC, brunasilvazup submitted a review, later dismissed

2021-02-05 17:09 UTC, henriquemoraeszup requested changes
Can you update the readme on how to create translations, which files to edit, which order to add a new term (is it alphabetic? by package?)

2021-04-27 15:00 UTC, brunasilvazup commented on internal/pkg/config/config_test.go
> +			if tt.want == nil {
`else` here?

2021-04-27 17:37 UTC, brunasilvazup approved these changes

2021-04-27 19:19 UTC, kaduartur commented on internal/pkg/config/config_test.go
> +			if tt.want == nil {
Makes a lot of sense rsrs

2021-04-28 18:40 UTC, kaduartur commented
/merge qa

2021-04-29 12:58 UTC, brunasilvazup approved these changes
🥇

2021-04-29 14:36 UTC, henriquemoraeszup approved these changes

2021-04-29 14:36 UTC, merged