[858] Adding feature containsAny, containsAll, containsOnly, notContainsAny and notContainsAll in conditional options
ZupIT/ritchie-cli pull request #874
Opened 2021-02-26 11:45 UTC by andressaabreuzup

Signed-off-by: Finzi <andressa.abreu@zup.com.br>
Issue: https://github.com/ZupIT/ritchie-cli/issues/858

### Description
Adding feature containsAny, containsAll, containsOnly, notContainsAny and notContainsAll in conditional options

### How to verify it
Create a formula with the new conditional options.

Example of a config.json with containsAny:

```json
[
	{
		"name": "sample_multiselect",
		"type": "multiselect",
		"items": [
			"item_1",
			"item_2",
			"item_3",
			"item_4"
		],
		"label": "Choose one or more items: ",
		"required": false,
		"tutorial": "Select one or more items for this field."
	},
	{
		"name": "sample_text",
     	        "type": "text",
		"label": "Type : ",
		"default": "test",
		"condition": {
			"variable": "sample_multiselect",
			"operator": "containsAny",
			"value":    "item_2|item_3"
		}
	}
]
```

### Changelog
Adding feature containsAny, containsAll, containsOnly, notContainsAny and notContainsAll in conditional options

2021-02-26 12:12 UTC, henriquemoraeszup commented on pkg/formula/input/input.go
> +		return !valueContainsAll(value, input.Condition.Value), nil
I was thinking this feature could work for `string contains` as well, shouldnt it? For example:
Input `carWash`
Conditional value `car` // should return true

Here seems to be handling only array contains

2021-02-26 12:12 UTC, henriquemoraeszup commented on pkg/formula/input/prompt/prompt_test.go
> +		want             error
You can remove the `want` if you are not expecting an error in any test

2021-02-26 12:12 UTC, henriquemoraeszup commented on pkg/formula/input/prompt/prompt_test.go
> +			name: "error multiselect input test with conditional containsAny",
I would change the `error` word in the test description, it seems like we are expecting a system error. Maybe something like `fail case`, what do you think? Same applies for the other tests as well

2021-02-26 12:12 UTC, henriquemoraeszup commented on pkg/formula/input/prompt/prompt_test.go
> +			assert.Equal(t, tt.want, got)
This is testing only if you do not get an error, but does not test if the cases evaluated correctly. You might want to invoke `VerifyConditional` manually and test if the `bool` signature matches your expected response

2021-03-02 13:28 UTC, brunasilvazup commented on pkg/formula/input/prompt/prompt.go
> +func (in InputManager) InputsConditionals(cmd *exec.Cmd, setup formula.Setup, f *pflag.FlagSet) (bool, error) {
I noticed that the Boolean return parameter is not used in the function called, so is there any reason for it to be returned?

We already had some conditional inputs and in line 97 they are considered, so I couldn't understand the reason for changing this method, could you explain?

2021-03-02 13:33 UTC, andressaabreuzup commented on pkg/formula/input/input.go
> +		return !valueContainsAll(value, input.Condition.Value), nil
this feature was designed for the case of multiselect, so the string passed by parameter must match exactly with the strings of the multiselect options, and not with substrings.

2021-03-02 13:34 UTC, andressaabreuzup commented on pkg/formula/input/prompt/prompt_test.go
> +		want             error
I change to want a bool, true in case of succes verify conditional and false in case of fail

2021-03-02 13:34 UTC, andressaabreuzup commented on pkg/formula/input/prompt/prompt_test.go
> +			name: "error multiselect input test with conditional containsAny",
done

2021-03-02 13:41 UTC, andressaabreuzup commented on pkg/formula/input/prompt/prompt_test.go
> +			assert.Equal(t, tt.want, got)
Calling VerifyConditional manually was generating a high complexity for the test since it is called several times and uses the cache of the previous call to finally test the conditional. I was copying the code of the func Inputs in the test and even so I didn't have all the necessary settings, so I thought about returning the conditionPass in the case of the conditional verification

2021-03-02 13:44 UTC, brunasilvazup commented on pkg/formula/input/prompt/prompt_test.go
> +func TestConditionalInputsWithMultiselect(t *testing.T) {
In these tests, an alternative to reduce the lines a bit is to put the inputJson of each type of test in variables, but I don't know if that would decrease the reading, @henriquemoraeszup what do you think?

2021-03-02 13:46 UTC, brunasilvazup commented on pkg/formula/input/prompt/prompt_test.go
> +		},
Repeated test?

2021-03-02 13:47 UTC, brunasilvazup commented on pkg/formula/input/prompt/prompt_test.go
> +			name: "fail: multiselect input test with conditional containsOnly",
This and the test below are valid but have the same name, when the tests runs one will overlap the result of the other.
Can you fix the names?

2021-03-02 13:51 UTC, brunasilvazup commented on pkg/formula/input/prompt/prompt_test.go
> +		},
Repeated test?

2021-03-02 13:54 UTC, andressaabreuzup commented on pkg/formula/input/prompt/prompt_test.go
> +func TestConditionalInputsWithMultiselect(t *testing.T) {
each inputJson is different for each test, in this case, I think that the code be inside the test makes it easier to read

2021-03-02 13:56 UTC, brunasilvazup commented on pkg/formula/input/prompt/prompt_test.go
> +		},
Does this test case fail in the same situation as the top one, looking at the logic, right?

2021-03-02 14:19 UTC, andressaabreuzup commented on pkg/formula/input/prompt/prompt_test.go
> +		},
No because the top case has an element (3) in the middle of the multiselect options that the user select that does not belong to the conditional parameters (2 and 4). 

I made two similar tests:
one with two conditional options (2 and 4) and three multiselect (2, 3 and 4) 
one with two conditional options (2 and 4) and two multiselect (2 and 4) 

because I check the size of the two arrays (conditional options and multiselect) in the case of notContainsAll, 
because to contain only and exclusively all the elements, the arrays must at least have the same size

2021-03-02 14:23 UTC, andressaabreuzup commented on pkg/formula/input/prompt/prompt_test.go
> +		},
There is no repeated test, the tests are a combination of:

- conditional operator (containsAny, containsAll, containsOnly, notConatinsAny and notContainsAll)
- conditional value separated by "|"
- select options of multiselect select by user separated by "|"

2021-03-02 14:29 UTC, andressaabreuzup commented on pkg/formula/input/prompt/prompt_test.go
> +			name: "fail: multiselect input test with conditional containsOnly",
Can I write like:

fail: multiselect input test with conditional containsOnly - fail because should contains only item_1 and item_2 and the values selected on multiselect by the user contains item_1, item_2 and item_3?

Im ifraid of to be repetitive

2021-03-02 18:59 UTC, henriquemoraeszup commented on pkg/formula/input/input.go
> +		return !valueContainsAll(value, input.Condition.Value), nil
I am a bit confused with this approach, we might need more discussing. We are restraining a conditional to a specific input type. It might not always be clear for the user to interpret this. Should we prefix with `multi`? Like `multiselectContainsAll`?

2021-03-03 18:47 UTC, brunasilvazup commented on pkg/formula/input/prompt/prompt_test.go
> +			name: "fail: multiselect input test with conditional containsOnly",
As discussed in Call, I think you can add a 'when selected list has more / less elements'

2021-03-03 18:49 UTC, brunasilvazup commented on pkg/formula/input/prompt/prompt_test.go
> +func TestConditionalInputsWithMultiselect(t *testing.T) {
Ok, sorry I think I made a mistake in the analysis
Follow the game :video_game:

2021-03-03 18:50 UTC, brunasilvazup commented on pkg/formula/input/prompt/prompt_test.go
> +		},
Like talking on Call, I was referring to two other tests that only have different items, but test the same use case. (:

2021-03-03 18:50 UTC, brunasilvazup commented on pkg/formula/input/prompt/prompt_test.go
> +		},
Like talking on Call, I was referring to two other tests that only have different items, but test the same use case. (:

2021-03-03 19:01 UTC, brunasilvazup commented on pkg/formula/input/prompt/prompt_test.go
> +		},
As we talked at call, I had referred to the line tests (886 and 917) that test the same use case, but exchange the test items.

2021-03-11 18:49 UTC, andressaabreuzup commented on pkg/formula/input/input.go
> +		return !valueContainsAll(value, input.Condition.Value), nil
Now supports multiselect and string

2021-03-11 18:51 UTC, andressaabreuzup commented on pkg/formula/input/prompt/prompt_test.go
> +			assert.Equal(t, tt.want, got)
I invoked VerifyConditional manually and tested if the bool signature matches with my expected response

2021-03-11 18:52 UTC, andressaabreuzup commented on pkg/formula/input/prompt/prompt.go
> +func (in InputManager) InputsConditionals(cmd *exec.Cmd, setup formula.Setup, f *pflag.FlagSet) (bool, error) {
I returned the original signature of the method

2021-03-11 18:52 UTC, andressaabreuzup commented on pkg/formula/input/prompt/prompt_test.go
> +			name: "fail: multiselect input test with conditional containsOnly",
done

2021-03-11 18:55 UTC, andressaabreuzup commented on pkg/formula/input/prompt/prompt_test.go
> +		},
done

2021-03-11 18:55 UTC, andressaabreuzup commented on pkg/formula/input/prompt/prompt_test.go
> +		},
done

2021-03-11 21:08 UTC, brunasilvazup commented on pkg/formula/input/input.go
> +		if !(strings.EqualFold(strings.ToLower(value), strings.ToLower(input))) {
The function EqualFold it's case-insensitivity, then i think that functions `toLower` it's unecessary.

And the parentheses involving the `strings.EqualFold([...])` to use `!` are not necessary too.

Do you can check this cases?

2021-03-15 11:21 UTC, andressaabreuzup commented on pkg/formula/input/input.go
> +		if !(strings.EqualFold(strings.ToLower(value), strings.ToLower(input))) {
done

2021-03-15 19:34 UTC, henriquemoraeszup commented on pkg/formula/input/input.go
> +	return true
I think you can simplify this line
```suggestion
	} else {
		return strings.EqualFold(value, input)
	}
```

2021-03-15 19:34 UTC, henriquemoraeszup commented on pkg/formula/input/flag/flag.go
> +	TypeSuffix              = "_type"
What is this used for?

2021-03-15 19:48 UTC, andressaabreuzup commented on pkg/formula/input/flag/flag.go
> +	TypeSuffix              = "_type"
To save the type of the variable without repeating its name in envVal.
Now envVal would look like this, for example:

RIT_SAMPLE_INPUT=item_1
RIT_SAMPLE_INPUT_TYPE=multiselect

The type was necessary because I need to know the type of variables to use the conditional "contains", because it has two different treatments for string and multiselect

2021-03-15 19:55 UTC, andressaabreuzup commented on pkg/formula/input/input.go
> +	return true
done

2021-03-16 13:16 UTC, henriquemoraeszup submitted a review, later dismissed
Hey, just a comment, but looks good 💯

2021-03-16 13:16 UTC, henriquemoraeszup commented on pkg/formula/input/prompt/prompt_test.go
> +			assert.Equal(t, tt.want.conditionalResult, result)
nice tests :clap:

2021-03-16 13:16 UTC, henriquemoraeszup commented on pkg/formula/input/flag/flag.go
> +	TypeSuffix              = "_type"
got it, just a convention, one underscore seems to make part of the variable name. For instance if I create a formula with `type` then I would get the env `type_type` which might be semantically confusing. Some frameworks like Django use double underscore to simulate accessing a property, how about we use this convention? For instance `RIT_SAMPLE_INPUT__TYPE` tries to represent `RIT_SAMPLE_INPUT.type`

2021-03-16 18:20 UTC, brunasilvazup commented on pkg/formula/input/prompt/prompt_test.go
> +		error             error
An suggestion: this error is all the time nil, so do you can simplify with remove this variable and with `assert.Nil(got)` in line 1218.

2021-03-16 18:21 UTC, brunasilvazup commented on pkg/formula/input/prompt/prompt_test.go
> +		error             error
The same suggestion in applicable here.

2021-03-16 18:24 UTC, brunasilvazup approved these changes
I left some suggestions, but it's up to you.

Independent, great functionality, congratulations :clap:  (:

2021-03-16 20:26 UTC, kaduartur commented
/merge qa

2021-03-16 21:49 UTC, kaduartur commented
/merge qa

2021-03-17 14:57 UTC, kaduartur requested changes

2021-03-17 14:57 UTC, kaduartur commented on pkg/formula/input/input.go
> +func containsArray(s []string, str string) bool {
Could you replace this function with `sliceutil.Contains`?

2021-03-17 14:57 UTC, kaduartur commented on pkg/formula/input/input.go
> +	splitInput := strings.Split(input, "|")
Could you use the constant `MultiselectSeparator` to avoid `"|"`?

2021-03-17 14:57 UTC, kaduartur commented on pkg/formula/input/input.go
> +	} else {
Do you need this `else` statement?

2021-03-17 14:57 UTC, kaduartur commented on pkg/formula/input/input.go
> +	} else {
Do you need this `else` statement?

2021-03-17 14:57 UTC, kaduartur commented on pkg/formula/input/input.go
> +	var typeValue string
Could you move these variables to before the "for" instruction at line 138?

2021-03-17 14:57 UTC, kaduartur commented on pkg/formula/input/input.go
> +	case "containsAny":
Does it make sense to create constants for these cases?

2021-03-17 17:29 UTC, andressaabreuzup commented on pkg/formula/input/input.go
> +	case "containsAny":
resolved in call

2021-03-17 17:30 UTC, andressaabreuzup commented on pkg/formula/input/input.go
> +	splitInput := strings.Split(input, "|")
done

2021-03-17 17:42 UTC, kaduartur commented
/merge qa

2021-03-17 17:53 UTC, kaduartur approved these changes
LGTM 🚀

2021-03-17 17:56 UTC, merged