Remove formula tmp dir
ZupIT/ritchie-cli pull request #875
Opened 2021-02-26 13:48 UTC by kaduartur

### Description
The need to copy the formula to a temporary folder has been removed, thus reducing the necessary IO when executing a formula.

### How to verify it
This improvement should not change the functionality of the rit.

### Changelog
Performance - remove tmp dir to formulas

2021-03-02 14:36 UTC, lucasdittrichzup approved these changes

2021-03-02 16:59 UTC, henriquemoraeszup commented
can you make an issue and link to your project?

2021-03-02 18:16 UTC, henriquemoraeszup commented on pkg/formula/runner/docker/runner_test.go
> +			_ = os.Chdir(pwd)
Can we test for file creation on the correct dir? This is the purpose of this PR correct?

2021-03-02 18:16 UTC, henriquemoraeszup commented on pkg/formula/runner/local/runner_test.go
> +				assert.EqualError(t, got, tt.want.Error())
Same here

2021-03-02 18:17 UTC, henriquemoraeszup requested changes
Just requesting since it was already approved

2021-03-03 18:30 UTC, kaduartur commented on pkg/formula/runner/docker/runner_test.go
> +			_ = os.Chdir(pwd)
Which file? this PR just stops copying the `/bin` folder of a formula to a tmp folder.

2021-03-03 19:41 UTC, victor-schumacher submitted a review, later dismissed

2021-03-03 20:04 UTC, brunasilvazup submitted a review, later dismissed

2021-03-03 20:07 UTC, kaduartur commented
/merge qa

2021-03-03 20:13 UTC, kaduartur commented
/merge qa

2021-03-04 11:17 UTC, henriquemoraeszup approved these changes
🎖️

2021-03-04 11:51 UTC, henriquemoraeszup commented
/merge qa

2021-03-04 14:00 UTC, henriquemoraeszup requested changes
The `pwd` of the formulas are correct, but if you create a formula with code that creates a file, on the first run the file will be created on the `.rit` folder. Subsequent runs creates on the user `pwd`

The formula has to create a file **before** its first build

2021-03-04 14:01 UTC, henriquemoraeszup commented
It would be interesting to simulate an execution that creates a file and checks its creation on the correct folder

2021-03-05 14:46 UTC, kaduartur commented
> The `pwd` of the formulas are correct, but if you create a formula with code that creates a file, on the first run the file will be created on the `.rit` folder. Subsequent runs creates on the user `pwd`
> 
> The formula has to create a file **before** its first build

I fixed this bug in [this](https://github.com/ZupIT/ritchie-cli/pull/875/commits/2259b48ed152dfda34c44f8805f573e66e7ebac0) commit

2021-03-05 18:39 UTC, henriquemoraeszup commented on pkg/formula/runner/docker/runner_test.go
> +				assert.FileExists(t, fileCreted)
* fileCreated

2021-03-05 18:40 UTC, henriquemoraeszup commented on pkg/formula/runner/local/pre_run_test.go
> -			name: "create work dir error",
code deletion ❤️

2021-03-05 18:41 UTC, henriquemoraeszup commented
/merge qa

2021-03-05 18:42 UTC, henriquemoraeszup commented
/merge qa

2021-03-08 13:33 UTC, brunasilvazup approved these changes

2021-03-08 14:13 UTC, henriquemoraeszup commented
The implementation is breaking on Windows, just create a formula and run to see

2021-03-10 11:09 UTC, henriquemoraeszup commented
/merge qa

2021-03-10 15:52 UTC, henriquemoraeszup approved these changes

2021-03-10 15:53 UTC, merged