feat: capture formula output
ZupIT/ritchie-cli pull request #900
Opened 2021-03-24 19:57 UTC by lucasdittrichzup

### Description

### How to verify it

### Changelog

2021-04-13 21:23 UTC, GuillaumeFalourd requested changes
Good job 👍🏼 

I just made an observation regarding the output space split as it seems to me this could be a problem for output variables with spaces.

The rest looks good to me 🚀

2021-04-13 21:23 UTC, GuillaumeFalourd commented on pkg/formula/runner/local/runner.go
> +		output := strings.Split(data[i], " ")[1:]
This split for space looks dangerous to me. What if the variable has a space inside it?

2021-04-13 21:43 UTC, fernandobelettizup commented on pkg/formula/runner/local/runner.go
> +		value := test[1]
Hey Lucas, how is it going?

I ran into a bug, but I am not sure if we should fix it in the code itself or by convention.

What happens is that when using a argument that has spaces within it (after splitting the data) there will not be a `key `and `value` within the `test` variable, and calling `test[1]` will break the program.

**How to Verify It**
- Create a formula and edit the default code, so that it contains the code you provided:
```
fmt.Printf("::output arg1=%s arg2=%s argN", arg1, arg2, argN)
```
- When testing the new formula, in this case, add a name with spaces:

![image](https://user-images.githubusercontent.com/60020008/114622542-78215a80-9c84-11eb-8d7c-7018317deba6.png)

- When execution reaches `transformData`, `data` will look like

![image](https://user-images.githubusercontent.com/60020008/114622821-d8b09780-9c84-11eb-8cdb-90ea9ff21c08.png)

- Since `data[1]`, has no `=`, when you split it, `test` will not have `length == 2` and you will get a panic message when trying to assign `value`
```
panic: runtime error: index out of range [1] with length 1
```
**Suggestion**
I thought about it and came with some ideas and think that solving this issue will need some more discussion.
1. By convention, we assume (and alert users) that in order to formula output feature work as intended no spaces are allowed in the input. Leaving it up to the user to check for spaces and, i.e, replacing these with dashes or underscores.
2. We check data before spliting it, i.e, looking for `=` sign and in case it is not there, we assume it is a tail of the previous `value`. At first glance it seems to work, but I do not know if it is scalable.

2021-04-14 13:03 UTC, GuillaumeFalourd commented on pkg/formula/runner/local/runner.go
> +		value := test[1]
A third option could also be to split using another caracter instead of `space` here:     
```
fmt.Printf("::output arg1=%s arg2=%s argN=%s", arg1, arg2, argN)
```

2021-04-14 13:17 UTC, GuillaumeFalourd commented on pkg/formula/runner/local/runner.go
> +		value := test[1]
Suggestion: use `--` to split. In that case, the print should look like this:

fmt.Printf("::output --arg1=%s --arg2=%s --argN=%s", arg1, arg2, argN)

As the `--` is already used as input flag, it won't be something new for the user.

2021-04-14 17:20 UTC, henriquemoraeszup commented
@lucasdittrichzup my suggestion is to turn off this feature, but merge the code. Then, you can implement Cobra's flag parsing feature from this string from another branch just to not make this one too big

2021-04-14 17:30 UTC, brunasilvazup requested changes
I have a question, will this output not work for formula executed via docker or will it be implemented in another pr?

2021-04-14 17:32 UTC, henriquemoraeszup commented on pkg/formula/runner/local/runner.go
> +		transformOutput := transformData(flattenOutput)
all these methods are creating sequential loops, I wonder if we could have some file `output.go` to isolate the logic and handle output processing and if it can process a line and write into a file, what do you think?

2021-04-14 17:33 UTC, henriquemoraeszup commented on pkg/formula/runner/local/runner.go
> +func writeOutput(setup formula.Setup, data map[string]string) error {
I think the `output` file should handle the writing as well

2021-04-16 20:01 UTC, lucasdittrichzup commented on pkg/formula/runner/local/runner.go
> +		transformOutput := transformData(flattenOutput)
I agree

2021-04-16 20:01 UTC, lucasdittrichzup commented on pkg/formula/runner/local/runner.go
> +func writeOutput(setup formula.Setup, data map[string]string) error {
Yep

2021-04-16 20:05 UTC, lucasdittrichzup commented on pkg/formula/runner/local/runner.go
> +		output := strings.Split(data[i], " ")[1:]
as I have other items to adjust, this first part will be off in production and I will upload the necessary changes to another PR

2021-04-16 20:08 UTC, lucasdittrichzup commented on pkg/formula/runner/local/runner.go
> +		value := test[1]
Thanks for the suggestion guys! @GuillaumeFalourd , the convention we adopted is `... arg1={arg1}, argN={argN}` and will be adjusted in another PR

2021-04-16 20:09 UTC, lucasdittrichzup commented
> I have a question, will this output not work for formula executed via docker or will it be implemented in another pr?

That's right @brunasilvazup , the idea is to have a local beta and only then implement it for the docker

2021-04-19 17:31 UTC, brunasilvazup approved these changes

2021-04-19 18:08 UTC, fernandobelettizup approved these changes

2021-04-22 13:24 UTC, lucasdittrichzup commented
/merge qa

2021-04-22 13:50 UTC, GuillaumeFalourd approved these changes

2021-04-22 19:59 UTC, merged