Friendlier error message on update repo
ZupIT/ritchie-cli pull request #903
Opened 2021-04-08 17:27 UTC by fernandobelettizup

### Description
This pull request improves the error message when `update repo` breaks in case of repositories changing visibility or being deleted.

New error messages follows:
`Error: could not retrieve new versions for selected repository`
`Please check if it still exists or changed visiblity`
`Try adding it again using:`
`rit add repo`

![image](https://user-images.githubusercontent.com/60020008/114069462-65b6b380-9875-11eb-9b72-6a28f5806881.png)

### How to verify it
Steps:
1. Clone this PR;
2. Build rit;
3. Using `rit add repo` add a public formula repository;
4. Delete or change its visibility;
5. Try updating it with `rit update repo`

### Changelog
Friendlier error message on update repo

2021-04-08 17:53 UTC, GuillaumeFalourd requested changes

2021-04-08 17:53 UTC, GuillaumeFalourd commented on pkg/git/bitbucket/repository.go
> +	`could not retrieve new versions for selected repository
Thinking about the DRY (Don't Repeat Yourself) concept, and as you used the same message for all git tools (BitBucket, Github, and Gitlab), don't you think we could use this message in only one place, instead of repeating the same message in each class?

2021-04-08 18:56 UTC, GuillaumeFalourd reviewed
LGTM 👍🏼  Well done! 🚀

2021-04-08 18:57 UTC, GuillaumeFalourd approved these changes

2021-04-08 18:59 UTC, henriquemoraeszup requested changes
Missing the tests for this case, you will have to simulate a 404 error

2021-04-08 18:59 UTC, henriquemoraeszup commented on pkg/git/gitlab/repository.go
>  	}
Can we extract this into a single function? It seems to be repeated

2021-04-08 20:26 UTC, fernandobelettizup commented
> Missing the tests for this case, you will have to simulate a 404 error

Added 404 error tests for each repo provider.
In addition, a 403 error test was added to Bitbucket repository tests file.
That being, because Github and Gitlab API returns a 404 error if the repo gets deleted or changed visibility, but when it comes to Bitbucket you can also get a 403 error if the repo became private.

2021-04-09 19:49 UTC, lucasdittrichzup approved these changes

2021-04-09 20:09 UTC, henriquemoraeszup approved these changes
Nice job! 👏

2021-04-09 20:23 UTC, merged

2021-04-09 20:47 UTC, henriquemoraeszup commented
@lucasdittrichzup this has been merged, but should still be tested in QA