Feature/create rename formula command
ZupIT/ritchie-cli pull request #907
Opened 2021-04-15 20:16 UTC by brunasilvazup

### Description

### How to verify it

### Changelog

2021-04-30 17:11 UTC, brunasilvazup commented on pkg/cmd/create_formula_test.go
> +				createForm = createFormulaCmdDeps(ritchieHomeDir, dirManager, fileManager)
This variable is unusable.

2021-04-30 18:32 UTC, henriquemoraeszup reviewed
I have a point to debate. I see that we take the workspace into account. Thinking about the user experience, making her know the workspace to run this command might add extra complexity to something simple. I know the name of the formula I currently have and I know what I want its new name to be. If I would rename a formula, I would update the directories names from a same workspace. So if you identify the workspace of a formula by name, you already know it is the same workspace for the new name. 

I understand workspace selection could play on formula disambiguation, but we should offer the best experience for the majority of cases. And I think it is safe to assume a regular user should have one of each formula. So I was thinking of a little inverted flow like:
```
old name
new name
resolve workspace (if not local, error, cannot rename repo formula)
rename formula
```

2021-04-30 18:32 UTC, henriquemoraeszup commented on pkg/cmd/create_formula_test.go
> +				createForm = createFormulaCmdDeps(ritchieHomeDir, dirManager, fileManager)
so maybe use `_ = createFormulaCmd...`

2021-04-30 19:57 UTC, brunasilvazup commented on pkg/cmd/create_formula_test.go
> +				createForm = createFormulaCmdDeps(ritchieHomeDir, dirManager, fileManager)
Oh no, the `tmpDir` in `createFormulaCmdDeps` method.

2021-04-30 20:03 UTC, brunasilvazup commented
> d workspace selection could play on formula disambiguation, but we should offer the best experience for the majority of cases. And I think it is safe to assume a regular user should have one of each formula

Do you suggest that the ritchie:
 - check if has only one workspace has the oldformula and
  - - true: continue with the process
  - - false: ask to user to select one of workspaces filtered?

2021-04-30 21:13 UTC, fernandobelettizup requested changes

2021-04-30 21:13 UTC, fernandobelettizup commented on pkg/cmd/rename_formula.go
> +func (r *renameFormulaCmd) changeFormulaToNewDir(fr formula.Rename) error {
What do you think about renaming this method to `moveFormulaToNewDir`?

2021-05-03 16:43 UTC, brunasilvazup commented on pkg/cmd/rename_formula.go
> +		question := fmt.Sprintf(questionConfirmation, result.OldFormulaCmd, result.NewFormulaCmd)
I think just the opposite, when the command comes via flag it is necessary to confirm it because typing errors can occur more easily.

2021-05-03 17:31 UTC, GuillaumeFalourd commented on pkg/cmd/rename_formula.go
> +		question := fmt.Sprintf(questionConfirmation, result.OldFormulaCmd, result.NewFormulaCmd)
I doubt this command will be used automatically, therefore I don't think there will be any problem to ask the user to confirm the option on the terminal (and if some users need this option in the future, it will be a quick implementation anyway).

2021-05-03 17:58 UTC, brunasilvazup commented on pkg/cmd/rename_formula.go
> +		question := fmt.Sprintf(questionConfirmation, result.OldFormulaCmd, result.NewFormulaCmd)
Hi @GuillaumeFalourd, do you think it is better to remove the rename confirmation or leave?

2021-05-03 18:07 UTC, GuillaumeFalourd commented on pkg/cmd/rename_formula.go
> +		question := fmt.Sprintf(questionConfirmation, result.OldFormulaCmd, result.NewFormulaCmd)
I believe it's safer to use a confirmation step. We can ask for users' feedbacks later as well to get more opinions about it.

2021-05-03 18:27 UTC, brunasilvazup commented on pkg/cmd/rename_formula.go
> +		defValue:    "",
If we assume this we use a default workspace, it may be necessary to confirm the values ​​at the end, what do you think?

2021-05-03 20:10 UTC, kaduartur requested changes

2021-05-03 20:10 UTC, kaduartur commented on pkg/formula/deleter/deleter.go
> +func NewDeleter(
Could you rename the function to `New()`?

2021-05-04 14:08 UTC, brunasilvazup commented on pkg/cmd/rename_formula.go
> +	ErrNonExistWorkspace = "The formula workspace '%s' does not exist, please enter a valid workspace"
I added this information `formula '%s' [...]` to make it clear which command cannot be used and why. I still think it's important principally when flags is used.

2021-05-07 13:13 UTC, brunasilvazup commented on pkg/formula/formula.go
> +	Rename struct {
Not really, thanks (:

2021-05-07 13:25 UTC, brunasilvazup commented on pkg/formula/validator/validator.go
> +	if strings.ContainsAny(v.formulaCMD, `\/><,@`) {
Hm, this is not really a constant, I will change it to be more explicit

2021-05-07 17:23 UTC, fernandobelettizup commented on pkg/cmd/rename_formula.go
> +	ErrNonExistWorkspace = "The formula workspace '%s' does not exist, please enter a valid workspace"
I agree with showing this information, but I was referring to the word `This`. For instance: 
In `This formula %q wasn't found in workspaces` I would suggest starting the sentence without `This`:
Resulting in: `Formula %q wasn't found in workspaces`

2021-05-07 21:43 UTC, GuillaumeFalourd approved these changes
Nice 👏🏼 
Make sure to update the documentation too with this new core command 😊 👍🏼

2021-05-12 12:01 UTC, kaduartur commented
/merge qa

2021-05-12 13:16 UTC, kaduartur commented
/merge qa

2021-05-24 15:06 UTC, merged