Feature/add formula rit list formulas
ZupIT/ritchie-cli pull request #913
Opened 2021-04-20 14:58 UTC by fernandobelettizup

### Description

Added command `rit list formula` (#857)
* Command available for prompt and input flags execution.
* Unit tests created for both cases.
* Formulas are listed based on selected repository or all repositories.
### How to verify it
* Run `rit list formula` and follow prompt instructions.
* Run `rit list formula --name=<repo_name>` to check for input flag compatibility.
* Run `rit lit formula --name=ALL` to list formulas from all repositories when using input flags.
### Changelog

Added command `rit list formula`

2021-04-20 16:58 UTC, GuillaumeFalourd commented on pkg/cmd/list.go
> +		Example:   "rit list repo, rit list credential, rit list workspace, rit list fomrula",
* `formula` (you spelled it wrong)

2021-04-22 12:45 UTC, brunasilvazup commented on internal/mocks/mocks.go
> +	args := t.Called()
Do you can add the parameter here?

2021-04-22 12:57 UTC, lucasdittrichzup commented on pkg/cmd/list_formula.go
> +		prompt.Warning("You don't have any repositories")
what do you think about making this sentence a const?

2021-04-22 13:03 UTC, brunasilvazup commented on pkg/cmd/list_formula.go
> +func (lr listFormulaCmd) runFormula() CommandRunnerFunc {
Here you could use a pointer `lr *listFormulaCmd`, what you think?

2021-04-22 13:07 UTC, brunasilvazup commented on pkg/cmd/list_formula.go
> +		}
The Repos type has a `Get` method, did you evaluate the use?

2021-04-22 13:19 UTC, brunasilvazup commented on pkg/cmd/list_formula.go
> +		return []formulaDefinition{}, errors.New("no repository with this name")
This error it's related with formulas right? So, what do you think to change the error to `errors.New("no formulas in this repository")` or `errors.New("not found formulas in this repository")`

2021-04-22 13:25 UTC, brunasilvazup commented on pkg/cmd/list_formula.go
> +		repos, err := lr.resolveInput(cmd)
I noticed that only the names of the repositories are used, how about changing the structure of Repos to [] String?

2021-04-22 13:28 UTC, brunasilvazup commented on pkg/cmd/list_formula.go
> +		repos, err := lr.resolveInput(cmd)
I noticed that only the names of the repositories are used, how about changing the structure of `Repos` to `[]String`?
And you can extract ALL resolver here too.

2021-04-22 13:41 UTC, fernandobelettizup commented on pkg/cmd/list_formula.go
> +		}
Hey Bruna,

I evaluated using it, and it works similarly to this for loop, but as it returns a `formula.Repo`.
In order to make it work, I would have to assign it to a new variable and then append to my slice.
It is pretty much the same, but also I would have to check for an extra error that was already covered when using `InputList`.

I am not sure, but it seems like it is not as fast as just checking for it straight forward.
What do you think about it?

Here is the way I coded in order to use `Get` method
```
repo, err := repos.Get(repoName)
if err != nil {
   return repoToListFormulas, err
}
repoToListFormulas = append(repoToListFormulas, repo)
```

2021-04-22 14:13 UTC, fernandobelettizup commented on pkg/cmd/list_formula.go
> +		return []formulaDefinition{}, errors.New("no repository with this name")
I am afraid in this case not.
`tree.Command` should only be empty if repo does not exist, because `tree.json` could not be found.
That being because when a repo does not have formulas, it cannot be added using `rit add repo`.

But your comment made me realize that maybe the repo exists and `tree.json` could be corrupted, folders might have been deleted, and repo still exists but no formulas could be retrieved.
I will change logic the check for both cases.

2021-04-22 15:17 UTC, fernandobelettizup commented on pkg/cmd/list_formula.go
> +		repos, err := lr.resolveInput(cmd)
The main reason why I am using `Repos` are because `RepositoryLister` return `Repos`.

For prompt execution, changing everything to `String` looks good. Because `repoNames` has already been extracted aiming to fill `InputList` and no further calculation is needed.

But when it comes to flags execution, if flag input is `"ALL"`, I will have to list repos (as it is right now) and also loop into repos to retrieve all repo names before sending this information to `printFormulas`.

That meaning that if I choose to work with `String` instead, I would have an extra loop execution for this specific case. And by using `Repos` this would not happen.

Do you agree with my analysis?

2021-04-22 16:56 UTC, brunasilvazup commented on pkg/cmd/list_formula_test.go
> +		{
You can add a test with the 'ALL' option via flags too. What about?

2021-04-22 16:56 UTC, brunasilvazup commented on pkg/cmd/list_formula_test.go
> +		},
You can also add a test with the 'ALL' option using flags. What about?

2021-04-22 17:02 UTC, brunasilvazup commented on pkg/cmd/list.go
> +		ValidArgs: []string{"credential", "repo", "workspace", "formula"},
Hello @fernandobelettizup, can you add the new formula in `Commands`- `api.go` so that the autocomplete works normally?

2021-04-22 17:04 UTC, brunasilvazup commented on pkg/cmd/list_formula.go
> +		}
I think I agree with your logic.
#FollowTheGame 👍🏾

2021-04-22 20:15 UTC, brunasilvazup commented on pkg/cmd/mocks_test.go
> +
Usually we remove functions from here, this function it's really necessary?

I not found were that is used.

2021-04-22 20:23 UTC, brunasilvazup commented on pkg/cmd/list_formula.go
> +		repos, err := lr.resolveInput(cmd)
I think it does make sense

2021-04-22 20:30 UTC, fernandobelettizup commented on pkg/cmd/mocks_test.go
> +
If we do not not implement this function on `mocks_test.go`, tests from `add_repo_test` and `formula_test` breaks.
That happens because used `treeMock` implements type `formula.Tree` that needs to have `TreeByRepo` method.

2021-04-22 20:33 UTC, brunasilvazup commented on pkg/cmd/list_formula.go
> +	reposNames = append(reposNames, listOptionAll)
You can simplify here with `reposNames := []string{listOptionAll}`

2021-04-22 20:38 UTC, brunasilvazup commented on pkg/cmd/mocks_test.go
> +
Oh it's true, right thanks for explanation (:

2021-04-22 20:42 UTC, brunasilvazup approved these changes
Good job, everything is fine with me 👍🏾

2021-04-23 13:38 UTC, henriquemoraeszup requested changes
Nice tests 🚀 just some points for debate

2021-04-23 13:38 UTC, henriquemoraeszup commented on pkg/cmd/list_formula.go
> +		return formula.Repos{}, errors.New("please provide a value for 'name'")
we have a method `missingFlagText` for standarization of an empty flag message

2021-04-23 13:38 UTC, henriquemoraeszup commented on pkg/cmd/list_formula.go
> +	repoFlagDescription = "Repository name to list formulas"
It is not expected that the user implicitly knows the use of the name `ALL`, you could add this note on the description

2021-04-23 13:38 UTC, henriquemoraeszup commented on pkg/cmd/list_formula.go
> +			return 0, err
If I have a single wrong name, I am aborting the whole process, should you ignore the failure or keep this approach? Just to think about it

2021-04-23 13:38 UTC, henriquemoraeszup commented on pkg/cmd/list_formula.go
> +			fd.Desc = cmd.Help
I think you could use a constructor. It is a more Gopher way
```
fd := formulaDefinition {
  Cmd: value,
  Desc: value2,
}
```

2021-04-23 13:38 UTC, henriquemoraeszup commented on pkg/cmd/list_formula_test.go
> +			assert.Equal(t, tt.want, got)
Since this command is about displaying a table, what do you think about checking for certain texts on `stdout`? `builder_test` has an example

2021-04-23 17:06 UTC, fernandobelettizup commented on pkg/cmd/list_formula.go
> +			return 0, err
Let us take a look at the prompt execution:
- User selects repo from repo input list, and we try to print formulas.
- Given that the repo name came from the input list, there should not be any wrong names, since input list only shows existing repos.

The only way we could face a wrong name error is when user tries to list formulas using input flags, in that case we kill the process before printing any rows of the table.

Although, if we are trying to print multiple repo formulas by selecting `ALL` option, it may happen that, when trying to read formulas an error occurs.
In this case what could be better?
Should we save faulty repo name, print all formulas and also a warning before the `[TUTORIAL]` section including a message similar to: 
```
Formulas from repoName could not be retrieved.
```
Or since we had an error when trying to retrieve all formulas we abort the whole process?

2021-04-23 18:10 UTC, fernandobelettizup commented on pkg/cmd/list_formula.go
> +	repoFlagDescription = "Repository name to list formulas"
I have thought of this message:
```
repoFlagDescription = "Repository name to list formulas, use 'ALL' to list formulas from all repositories."
```
When running `rit list formula --help` this would be the output:
![image](https://user-images.githubusercontent.com/60020008/115912359-98e86d80-a445-11eb-83f7-db488f75b299.png)

Is it ok? Or would it be better to add this note at the description (first line of output)?

2021-04-26 13:10 UTC, henriquemoraeszup commented on pkg/cmd/list_formula.go
> +	repoFlagDescription = "Repository name to list formulas"
that looks good enough

2021-04-26 13:13 UTC, henriquemoraeszup commented on pkg/cmd/list_formula.go
> +			return 0, err
if you abort the whole process from a missing repo in ALL, you are subjecting your user to learn how to fix Ritchie's configurations and preventing her from getting the output of the command. Adding a warning would allow the user to opt into correcting the problem without breaking its experience

2021-04-27 19:13 UTC, kaduartur requested changes

2021-04-27 19:24 UTC, fernandobelettizup commented on pkg/cmd/list_formula.go
> +func (lr *listFormulaCmd) runFormula() CommandRunnerFunc {
It seems to be a standard using `runFormula` on all files that use input flags.

2021-04-27 19:27 UTC, fernandobelettizup commented on pkg/cmd/list_formula.go
> +		repoToListFormulas = repos
I can return `repos`, but still need else statement just in case list option is not `ALL`, in this situation I would return `repos[i]`, instead of appending to the list.
What do you think about it?

2021-04-28 18:57 UTC, fernandobelettizup commented on pkg/cmd/list_formula.go
> +				return 0, err
For both `ALL` and single repo execution, error was converted into a warning message.
For instance, when running for `ALL`, there can happen two warnings, one for unknown error and one for no formulas in repo.
In any cases these warnings prevent process abortion.
![image](https://user-images.githubusercontent.com/60020008/116457445-cb290f00-a839-11eb-8dca-41a5e1500f17.png)

When running for only one repo, tutorial is also changed:
![image](https://user-images.githubusercontent.com/60020008/116457895-5a362700-a83a-11eb-9264-084651acac61.png)

What do you think about these changes?

2021-04-29 15:01 UTC, kaduartur submitted a review, later dismissed

2021-04-29 15:02 UTC, kaduartur commented
/merge qa

2021-04-30 14:21 UTC, henriquemoraeszup commented on pkg/cmd/list_formula.go
> +			}
Just curious, would we be able to remove all these conditionals and still get the same behavior? I mean, for a single repo just issue the warning. I know we would execute operations on a single item array like `Sort` but the processing power is negligible, and removing this code would reduce cognitive complexity

2021-04-30 14:23 UTC, henriquemoraeszup commented on pkg/cmd/list_formula_test.go
> +				_ = streams.Unzip("../../testdata/tree.zip", repoPath)
Should we join with path or is this ok? Wouldnt this break on windows?

2021-04-30 14:23 UTC, henriquemoraeszup submitted a review, later dismissed
Approving, but you should check the comments

2021-04-30 14:33 UTC, fernandobelettizup commented on pkg/cmd/list_formula_test.go
> +				_ = streams.Unzip("../../testdata/tree.zip", repoPath)
It works just fine on Windows too.

2021-04-30 15:08 UTC, fernandobelettizup commented on pkg/cmd/list_formula.go
> +			}
I do not see any problems just issuing the warning for a single repo.
In this case is it ok if I check for `allFormulas` length before running any table operation by moving all table related code to a conditional block?

```
if len(allFormulas) != 0 {
	table := uitable.New()
	table.AddRow("COMMAND", "DESCRIPTION")
	sort.Sort(ByCmd(allFormulas))
	for _, fm := range allFormulas {
		table.AddRow(fm.Cmd, fm.Desc)
	}
	raw := table.Bytes()
	raw = append(raw, []byte("\n")...)
	fmt.Println(string(raw))
}
```

2021-05-03 20:29 UTC, kaduartur submitted a review, later dismissed

2021-05-03 20:29 UTC, kaduartur commented
/merge qa

2021-05-04 13:37 UTC, kaduartur approved these changes

2021-05-04 13:38 UTC, kaduartur commented
/merge qa

2021-05-04 13:39 UTC, kaduartur commented
/merge qa

2021-05-04 13:48 UTC, merged