added input flags support
ZupIT/ritchie-cli pull request #923
Opened 2021-05-12 20:56 UTC by fernandobelettizup

### Description

Adding flag support to `rit set env` command.
### How to verify it
Run `rit set env --env=<env_name>` and check if it has been successfully set with `rit show env`.
### Changelog

Added flag support for rit set env command.

2021-05-12 21:25 UTC, henriquemoraeszup commented on pkg/cmd/set_env.go
> +
Should you ensure this env is valid? What happens if I provide a non existent name

2021-05-13 12:29 UTC, brunasilvazup commented on pkg/cmd/set_env.go
> +		env, err = s.Text("New env: ", true)
This `[...], true)` part guarantees values `> '' `?

2021-05-13 12:33 UTC, fernandobelettizup commented on pkg/cmd/set_env.go
> +
We do not have a `rit create env` command.
The set method, checks for an existent environment, if it does not exist it is created.

2021-05-13 12:35 UTC, fernandobelettizup commented on pkg/cmd/set_env.go
> +		env, err = s.Text("New env: ", true)
Yes, if you enter a blank name, ritchie returns `Sorry, your reply was invalid: Value is required`

2021-05-13 13:10 UTC, brunasilvazup commented on pkg/cmd/set_env.go
> +			return nil
If the value can't be nil, this logic it's necessary?

2021-05-17 13:22 UTC, lucasdittrichzup approved these changes

2021-05-19 16:45 UTC, GuillaumeFalourd commented
@fernandobelettizup : Would it be possible to add a unit test for the input flag scenario in the `set_env_test.go` file please?

2021-05-19 16:45 UTC, GuillaumeFalourd requested changes
@fernandobelettizup : Would it be possible to add a unit test for the input flag scenario in the `set_env_test.go` file please?

2021-05-19 17:48 UTC, fernandobelettizup commented
@GuillaumeFalourd There are 4 tests using input flags scenario.

2021-05-21 18:20 UTC, fernandobelettizup commented
This pull request was merged via #926

2021-05-21 18:20 UTC, closed without merging