support flags - rit init
ZupIT/ritchie-cli pull request #932
Opened 2021-05-25 18:09 UTC by maurineimirandazup

### Description

These changes are intended to improve the method of executing the `rit init` command. With them, the use of input flags will be allowed in the execution of the command.
### How to verify it
You can run the `rit init` command with the following flags:
`--sendMetrics=("yes", "no")` default: yes
`--addCommons=("yes", "no")` default: yes
`--runType=("local", "docker")` default: local
### Changelog

2021-06-04 22:56 UTC, brunasilvazup commented on pkg/cmd/init.go
> +	}
Here it is not being checked if the value provided is valid as well. How about putting a null value in `runType` and checking if it's still null at the end of the for?

2021-06-04 22:57 UTC, brunasilvazup commented on pkg/cmd/init.go
> +			return config.Configs{}, errors.New("please provide a valid value to the flag 'sendmetrics'")
Here you can use the var `metricsFlag`.

2021-06-04 22:57 UTC, brunasilvazup commented on pkg/cmd/init.go
> +	},
Hi @maurineimirandazup,
I don't know if these variables should have default values ​​set, because by some error the user may have a choice that he didn't make (download new repositories, accept having his data collected).
Maybe @GuillaumeFalourd can contribute, but I think it's safer for the user not to have the answers by default.

And you can use the kind `reflect.Bool` if you want restrict the values, but I dont know how to `true or false` can be accept to UX.

2021-06-10 19:56 UTC, maurineimirandazup commented on pkg/cmd/init.go
> +	switch metrics {
This was the initial proposal, but in stdin and in the prompt, these logics were already repeated. In an internal discussion, it was decided to open an ISSUE to refactor all this part into the next version.

2021-06-10 20:03 UTC, maurineimirandazup commented on pkg/cmd/init.go
> +	},
The proposal to use reflect.Bool was indeed interesting, but for that we would have to make changes to the flags lib, so as discussed, I used another approach that comes close to this idea.

2021-06-10 20:04 UTC, maurineimirandazup commented on pkg/cmd/init.go
> +			return config.Configs{}, errors.New("please provide a valid value to the flag 'sendmetrics'")
Done.

2021-06-10 20:04 UTC, maurineimirandazup commented on pkg/cmd/init.go
> +		return config.Configs{}, errors.New("please provide a valid value to the flag 'addCommons'")
Done.

2021-06-10 20:04 UTC, maurineimirandazup commented on pkg/cmd/init.go
> +	}
Done.

2021-06-11 14:40 UTC, GuillaumeFalourd requested changes

2021-06-11 14:40 UTC, GuillaumeFalourd commented on pkg/cmd/init.go
> +	boolOpts := map[string]bool{
It could be interesting to use the map variable from this class instead: https://github.com/ZupIT/ritchie-cli/blob/af0a183d47cbf2f814abb23c38407f4a77223621/pkg/prompt/bool.go#L24 to avoid repeating the same code.

2021-06-11 16:32 UTC, GuillaumeFalourd approved these changes
Just fix the linter. The rest looks good to me, well done!👍🏼

2021-06-11 20:11 UTC, GuillaumeFalourd approved these changes
👍🏼

2021-06-11 20:42 UTC, brunasilvazup approved these changes

2021-06-14 13:25 UTC, merged