Improve list workspace with status of path
ZupIT/ritchie-cli pull request #933
Opened 2021-05-26 02:40 UTC by fabianofernandeszup

Signed-off-by: fabianofernandeszup <fabiano.fernandes@zup.com.br>

### Description
The list of workspaces shows paths that may have already been deleted. This improvement displays a status column and validates if the path still exists or if the reference has been broken. 

![image](https://user-images.githubusercontent.com/58859234/119594627-85b51e80-bdb2-11eb-86d5-1f5fe1413ca6.png)

### How to verify it
Run the rit list workspace command

### Changelog
Added workspaces path status column

2021-05-26 13:38 UTC, lucasdittrichzup submitted a review, later dismissed

2021-05-26 13:57 UTC, GuillaumeFalourd requested changes

2021-05-26 13:57 UTC, GuillaumeFalourd commented on pkg/cmd/list_workspace.go
> +		return "Path not found"
It would be interesting to add a test for this scenario on the `list_workspace_test.go`

2021-06-07 13:26 UTC, GuillaumeFalourd commented
@fabianofernandeszup , it seems your Pull Request is containing contributions related to different things: 
- the `list workspace` upgrade
- the docker runner usage
- new github actions workflows

Could you please separate those contributions for better support and traceability?

(*Obs: There is still new tests to implement related to your list workspace upgrade*) 😄

2021-06-08 13:27 UTC, GuillaumeFalourd commented
Has been reopened here: https://github.com/ZupIT/ritchie-cli/pull/954

2021-06-08 13:27 UTC, closed without merging