Support flags to metrics command
ZupIT/ritchie-cli pull request #973
Opened 2021-06-29 12:40 UTC by maurineimirandazup

### Description
Flags support for the `metrics` command
### How to verify it
`rit metrics --metrics="yes"`
### Changelog

2021-07-01 18:32 UTC, GuillaumeFalourd requested changes

2021-07-01 18:32 UTC, GuillaumeFalourd commented on pkg/cmd/metrics.go
> +		"You want to send anonymous data about the product, feature use, statistics and crash reports?",
Use `Do you want to` please, as it's a question.

2021-07-01 18:37 UTC, maurineimirandazup commented on pkg/cmd/metrics.go
> +		"You want to send anonymous data about the product, feature use, statistics and crash reports?",
Done!

2021-07-01 18:39 UTC, GuillaumeFalourd requested changes
Good implementation. Well done! 👍🏼  

Now, you need to add `rit metrics` functional tests on the [github actions global workflow](https://github.com/ZupIT/ritchie-cli/blob/master/.github/workflows/test-global-commands.yml) following the [DEVELOPER GUIDE recommendations](https://github.com/ZupIT/ritchie-cli/blob/master/DEVELOPER_GUIDE.md#functional-tests)

2021-07-05 15:17 UTC, fabianofernandeszup approved these changes

2021-07-05 15:17 UTC, merged